// Gold Standard JoeAI Genome Cards — Pack 2.
// Curated personal-taste anchors for the active feature/anime-catalog branch.
// Add this file, then run: node scripts/installGoldPack2.cjs

export const GOLD_STANDARD_GENOME_CARDS_PACK_2 = [
  {
    id: "initial-d",
    titles: ["Initial D"],
    aliases: ["Initial D First Stage", "Initial D 1st Stage"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "street racing / mastery obsession",
    subdomain: "gold standard personal-taste anchor",
    signature: "A night-road racing classic where quiet talent, repetition, machine feel, Eurobeat, and mountain-pass pressure turn delivery driving into a legend.",
    coreFantasy: "Become so locked in with your car, road, and instincts that impossible corners feel natural and every race proves what quiet mastery can do.",
    fantasyPillars: ["hidden genius", "mechanical intimacy", "rival respect", "mountain-pass pressure", "skill over flash", "night-drive adrenaline"],
    emotionalJourney: ["routine", "curiosity", "pressure", "focus", "breakthrough", "legend status"],
    rewardLoop: ["new challenger", "car comparison", "course weakness", "technical insight", "Eurobeat race", "cornering breakthrough", "earned respect"],
    dopamineSources: ["Eurobeat race energy", "technical driving details", "underdog wins", "rival reactions", "car culture", "calm genius moments"],
    viewerType: ["mastery fan", "sports-rivalry fan", "car culture fan", "training-by-repetition fan"],
    viewerMotivations: ["skill growth", "rivalry", "technical details", "underdog dominance", "cool night atmosphere"],
    themes: ["mastery", "instinct", "discipline", "identity", "rivalry", "respect"],
    emotionalProfile: ["focused", "cool", "adrenaline-heavy", "nostalgic", "satisfying"],
    atmosphere: ["night roads", "mountain passes", "garage culture", "street racing", "90s energy"],
    vibes: { sports: 9, rivalry: 9, adrenaline: 10, technical: 9, nostalgia: 8 },
    pacing: "race-to-race escalation",
    complexity: 6,
    whyFansLove: ["the races feel tactical and emotional", "Takumi's quiet skill is addictive", "the music makes every pass hit harder", "rivals become part of the legend", "the show understands mastery through repetition"],
    whoShouldWatch: "Viewers who love underdog mastery, technical competition, rivalry, cars, and high-adrenaline payoffs without needing giant supernatural stakes.",
    whoShouldAvoid: "Skip if you need polished modern animation, huge fantasy worlds, or dislike racing structure.",
    idealFollowUps: ["megalo-box", "haikyu", "run-with-the-wind", "slam-dunk", "yowamushi-pedal"],
    joeNote: "Gold personal anchor. Weight mastery, technical rivalry, underdog calm, and adrenaline higher than simple sports tags."
  },
  {
    id: "dorohedoro",
    titles: ["Dorohedoro"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "grimy weird fantasy / chaotic found family",
    subdomain: "gold standard weird-chaos anchor",
    signature: "A filthy, funny, violent, strangely warm nightmare about lizard heads, sorcerers, gyoza, body horror, and lovable freaks surviving a world with no clean edges.",
    coreFantasy: "Live inside a bizarre hellhole where everyone is dangerous, everyone is weird, and somehow the chaos feels like home.",
    fantasyPillars: ["grimy urban fantasy", "body horror comedy", "lovable monsters", "surreal magic rules", "found family by violence", "punk food-and-blood energy"],
    emotionalJourney: ["confusion", "disgust", "laughter", "attachment", "shock", "strange warmth"],
    rewardLoop: ["weird mystery", "gross magic", "violent encounter", "absurd comedy", "character hangout", "deeper conspiracy"],
    dopamineSources: ["bizarre worldbuilding", "gross-out surprises", "dark comedy", "Caiman and Nikaido chemistry", "sorcerer faction chaos", "food scenes"],
    viewerType: ["weird fiction fan", "dark comedy fan", "seinen chaos enjoyer", "cult anime fan"],
    viewerMotivations: ["originality", "griminess", "absurd humor", "mystery", "violent charm"],
    themes: ["identity", "class divide", "friendship", "survival", "memory", "monstrosity"],
    emotionalProfile: ["gross", "funny", "violent", "warm", "surreal"],
    atmosphere: ["industrial", "filthy", "punk", "nightmarish", "cozy in a broken way"],
    vibes: { weird: 10, darkComedy: 10, gore: 8, mystery: 8, foundFamily: 7 },
    pacing: "chaotic mystery escalation",
    complexity: 8,
    whyFansLove: ["nothing else feels like it", "the ugly world is full of personality", "the cast is dangerous but lovable", "the humor cuts through the violence", "the mystery keeps the madness moving"],
    whoShouldWatch: "Viewers who want wild originality, grimy comedy, violent fantasy, and a cast of lovable freaks.",
    whoShouldAvoid: "Skip if gore, body horror, or deliberately messy weirdness turns you off.",
    idealFollowUps: ["chainsaw-man", "golden-kamuy", "made-in-abyss", "kaiba", "devilman-crybaby"],
    joeNote: "Gold weird anchor. This is not generic dark fantasy; weight grime, absurd comedy, body horror, food, and lovable chaos."
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    titles: ["Fullmetal Alchemist: Brotherhood"],
    aliases: ["FMAB", "Fullmetal Alchemist Brotherhood"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "complete epic fantasy / moral adventure",
    subdomain: "gold standard complete-story anchor",
    signature: "A tightly built adventure about two brothers trying to repair an unforgivable mistake while uncovering a national conspiracy built on grief, war, science, and sacrifice.",
    coreFantasy: "Chase redemption across a dangerous world where every power has a cost, every mistake leaves a scar, and every piece of the plot eventually matters.",
    fantasyPillars: ["brotherhood", "equivalent exchange", "military conspiracy", "earned redemption", "science-magic rules", "complete payoff"],
    emotionalJourney: ["guilt", "hope", "mystery", "rage", "sacrifice", "catharsis"],
    rewardLoop: ["new lead", "alchemy rule", "moral cost", "conspiracy reveal", "character sacrifice", "plot payoff"],
    dopamineSources: ["tight plotting", "alchemy mechanics", "emotional reveals", "ensemble cast", "villain structure", "complete ending"],
    viewerType: ["complete-story fan", "fantasy adventure fan", "plot payoff fan", "moral shonen fan"],
    viewerMotivations: ["redemption", "mystery", "brotherhood", "worldbuilding", "satisfying closure"],
    themes: ["sacrifice", "war guilt", "family", "truth", "redemption", "human value"],
    emotionalProfile: ["adventurous", "tragic", "hopeful", "heroic", "cathartic"],
    atmosphere: ["military fantasy", "industrial", "conspiratorial", "warm", "epic"],
    vibes: { adventure: 9, emotional: 9, mystery: 8, action: 8, payoff: 10 },
    pacing: "tight long-form escalation",
    complexity: 8,
    whyFansLove: ["the story pays off almost everything", "the brothers' bond gives the plot a soul", "the villains connect to the themes", "the world feels coherent", "the ending actually lands"],
    whoShouldWatch: "Viewers who want a complete emotional adventure with action, mystery, moral weight, and one of anime's most satisfying endings.",
    whoShouldAvoid: "Skip if you only want slice-of-life comfort or ultra-dark ambiguity without heroic payoff.",
    idealFollowUps: ["hunter-x-hunter-2011", "magi", "attack-on-titan", "made-in-abyss", "vinland-saga"],
    joeNote: "Gold complete-story anchor. Weight payoff, brotherhood, moral cost, and equivalent-exchange structure very high."
  },
  {
    id: "frieren-beyond-journeys-end",
    titles: ["Frieren: Beyond Journey's End"],
    aliases: ["Sousou no Frieren", "Frieren"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "quiet fantasy / memory and grief",
    subdomain: "gold standard gentle-emotional fantasy anchor",
    signature: "A reflective fantasy about an elf retracing what adventure meant after the hero's journey is already over, turning memory, grief, and small human moments into magic.",
    coreFantasy: "Walk through a beautiful world after the big victory and slowly understand that the ordinary moments with people were the treasure all along.",
    fantasyPillars: ["after-the-adventure", "immortal perspective", "quiet grief", "small kindnesses", "beautiful magic", "slow emotional realization"],
    emotionalJourney: ["distance", "nostalgia", "regret", "warmth", "wonder", "acceptance"],
    rewardLoop: ["new town", "old memory", "small request", "emotional realization", "magic detail", "gentle growth"],
    dopamineSources: ["quiet emotional payoffs", "beautiful fantasy travel", "subtle character growth", "magic-as-memory", "mentor/student bonds"],
    viewerType: ["quiet fantasy fan", "emotional reflection fan", "slow-burn character fan", "beautiful world fan"],
    viewerMotivations: ["healing", "memory", "meaning", "companionship", "melancholy comfort"],
    themes: ["time", "grief", "memory", "legacy", "friendship", "human connection"],
    emotionalProfile: ["gentle", "melancholic", "healing", "beautiful", "wise"],
    atmosphere: ["pastoral", "magical", "quiet", "bittersweet", "expansive"],
    vibes: { fantasy: 9, emotional: 10, cozy: 8, melancholy: 9, action: 5 },
    pacing: "slow reflective journey",
    complexity: 7,
    whyFansLove: ["it makes small moments feel enormous", "Frieren's emotional thaw is beautiful", "the fantasy world feels lived in", "the grief is gentle but powerful", "the action hits harder because it is rare"],
    whoShouldWatch: "Viewers who want reflective fantasy, emotional healing, travel, memory, and beauty more than constant battles.",
    whoShouldAvoid: "Skip if you need nonstop action or fast plot twists every episode.",
    idealFollowUps: ["mushishi", "violet-evergarden", "spice-and-wolf", "made-in-abyss", "to-your-eternity"],
    joeNote: "Gold quiet fantasy anchor. Weight melancholy, memory, healing, and after-the-adventure structure over normal fantasy quest tags."
  },
  {
    id: "world-trigger",
    titles: ["World Trigger"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "tactical sci-fi shonen / team strategy",
    subdomain: "gold standard strategy-combat anchor",
    signature: "A tactical team-battle shonen where formations, map control, roles, preparation, and clever teamwork matter more than yelling harder.",
    coreFantasy: "Win battles by thinking three moves ahead, using your team correctly, and turning weak-looking tools into smart advantages.",
    fantasyPillars: ["tactical combat", "team roles", "rank wars", "alien invasion", "strategy over power", "systems mastery"],
    emotionalJourney: ["curiosity", "training", "pressure", "analysis", "breakthrough", "team pride"],
    rewardLoop: ["match rules", "enemy comp", "map condition", "strategy adjustment", "team combo", "ranking gain"],
    dopamineSources: ["smart tactics", "team synergy", "rank-war structure", "loadout details", "underdog planning", "battle analysis"],
    viewerType: ["strategy fan", "team tactics fan", "battle-system nerd", "patient shonen fan"],
    viewerMotivations: ["outsmarting", "teamwork", "systems", "growth", "competitive structure"],
    themes: ["teamwork", "preparation", "adaptability", "discipline", "trust", "responsibility"],
    emotionalProfile: ["methodical", "satisfying", "competitive", "clever", "earnest"],
    atmosphere: ["organized", "military-lite", "simulation-like", "competitive", "sci-fi"],
    vibes: { strategy: 10, teamwork: 10, action: 7, worldbuilding: 7, hype: 7 },
    pacing: "systematic tactical escalation",
    complexity: 9,
    whyFansLove: ["fights are puzzles", "weak characters can matter through tactics", "team roles are meaningful", "the ranking system creates clear stakes", "planning pays off"],
    whoShouldWatch: "Viewers who love smart team battles, tactics, rank progression, and power systems that reward planning.",
    whoShouldAvoid: "Skip if you only want flashy animation, emotional melodrama, or instant power-up wins.",
    idealFollowUps: ["hunter-x-hunter-2011", "log-horizon", "haikyu", "aldnoah-zero", "blue-lock"],
    joeNote: "Gold tactical anchor. Weight planning, team roles, and system rules above generic sci-fi/action labels."
  },
  {
    id: "jujutsu-kaisen",
    titles: ["Jujutsu Kaisen"],
    aliases: ["JJK"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "modern supernatural battle shonen",
    subdomain: "gold standard modern-cursed-action anchor",
    signature: "A slick modern exorcist battle anime where cursed energy, brutal fights, mentorship, horror edges, and style turn shonen momentum into something sharp and dangerous.",
    coreFantasy: "Enter a hidden war against curses where talent, technique, and impossible mentors help you survive a world that punishes hesitation.",
    fantasyPillars: ["cursed energy", "modern exorcists", "stylish combat", "mentor swagger", "horror pressure", "brutal consequences"],
    emotionalJourney: ["shock", "hype", "fear", "confidence", "loss", "resolve"],
    rewardLoop: ["curse threat", "technique reveal", "team fight", "domain pressure", "mentor flex", "consequence"],
    dopamineSources: ["fluid fights", "domain expansions", "Gojo moments", "curse designs", "team chemistry", "brutal escalation"],
    viewerType: ["modern shonen fan", "supernatural action fan", "sakuga fan", "dark battle fan"],
    viewerMotivations: ["hype fights", "cool powers", "horror edge", "mentor charisma", "dangerous stakes"],
    themes: ["death", "duty", "fear", "friendship", "power", "sacrifice"],
    emotionalProfile: ["hype", "dark", "slick", "violent", "tense"],
    atmosphere: ["urban supernatural", "stylish", "cursed", "violent", "modern"],
    vibes: { action: 10, supernatural: 9, style: 9, dark: 8, emotional: 7 },
    pacing: "fast modern escalation",
    complexity: 7,
    whyFansLove: ["the fights are electric", "the power system feels stylish", "Gojo is instant charisma", "the horror edge keeps stakes sharp", "the cast has strong chemistry"],
    whoShouldWatch: "Viewers who want modern supernatural action with slick fights, dark stakes, curses, and high style.",
    whoShouldAvoid: "Skip if graphic violence or fast escalation bothers you.",
    idealFollowUps: ["bleach", "chainsaw-man", "demon-slayer", "hells-paradise", "yu-yu-hakusho"],
    joeNote: "Gold modern battle anchor. Weight style, curse horror, domain pressure, and brutal escalation."
  },
  {
    id: "gintama",
    titles: ["Gintama"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "absurd comedy / found-family samurai sci-fi",
    subdomain: "gold standard comedy-heart anchor",
    signature: "A chaotic samurai sci-fi comedy that weaponizes parody, stupidity, found family, and sudden emotional seriousness until the jokes become part of the heart.",
    coreFantasy: "Hang out with broke weirdos in a ridiculous world where every dumb bit might suddenly turn into loyalty, grief, or an all-time serious arc.",
    fantasyPillars: ["absurd comedy", "parody overload", "found family", "samurai soul", "sci-fi nonsense", "serious arcs that ambush you"],
    emotionalJourney: ["confusion", "laughter", "comfort", "surprise", "pain", "earned affection"],
    rewardLoop: ["stupid premise", "escalating bit", "character chaos", "reference gag", "sudden sincerity", "serious payoff"],
    dopamineSources: ["meta jokes", "cast chemistry", "running gags", "parody", "emotional whiplash", "Gintoki's hidden depth"],
    viewerType: ["comedy anime fan", "long-haul cast fan", "parody fan", "found-family chaos fan"],
    viewerMotivations: ["laughing", "hanging out", "cast attachment", "emotional surprise", "anime references"],
    themes: ["found family", "survival", "loyalty", "nostalgia", "honor", "moving forward"],
    emotionalProfile: ["ridiculous", "warm", "chaotic", "suddenly heartbreaking", "comforting"],
    atmosphere: ["Edo sci-fi", "slapstick", "meta", "rowdy", "surprisingly heartfelt"],
    vibes: { comedy: 10, parody: 10, foundFamily: 9, action: 6, emotional: 8 },
    pacing: "episodic chaos with serious arc spikes",
    complexity: 8,
    whyFansLove: ["the cast becomes family", "the dumbest jokes somehow build attachment", "serious arcs hit shockingly hard", "it parodies anime while loving anime", "Gintoki is a legendary comedy lead"],
    whoShouldWatch: "Viewers who want long-form comedy, parody, found family, and emotional payoffs hidden inside absurd nonsense.",
    whoShouldAvoid: "Skip if you need immediate plot momentum or dislike reference-heavy comedy.",
    idealFollowUps: ["sket-dance", "saiki-k", "grand-blue", "golden-kamuy", "one-piece"],
    joeNote: "Gold comedy-heart anchor. Weight hangout comfort, parody, found family, and serious-arc whiplash."
  },
  {
    id: "monster",
    titles: ["Monster"],
    aliases: ["Naoki Urasawa's Monster"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "psychological thriller / moral pursuit",
    subdomain: "gold standard slow-burn thriller anchor",
    signature: "A grounded psychological thriller about a doctor hunting the consequences of one saved life, where morality, identity, trauma, and evil unfold with patient dread.",
    coreFantasy: "Follow a moral man through a realistic nightmare, trying to stop a monster while refusing to become one.",
    fantasyPillars: ["moral pursuit", "realistic dread", "serial mystery", "identity horror", "slow-burn investigation", "human evil"],
    emotionalJourney: ["unease", "guilt", "obsession", "dread", "revelation", "moral resolve"],
    rewardLoop: ["new witness", "old trauma", "false lead", "ethical test", "Johan shadow", "psychological reveal"],
    dopamineSources: ["slow mystery reveals", "moral tension", "Johan's presence", "grounded suspense", "character studies", "European noir atmosphere"],
    viewerType: ["psychological thriller fan", "slow-burn mystery fan", "seinen drama fan", "crime story fan"],
    viewerMotivations: ["mystery", "moral complexity", "realism", "dread", "character depth"],
    themes: ["evil", "identity", "trauma", "morality", "choice", "human worth"],
    emotionalProfile: ["tense", "somber", "dreadful", "intelligent", "haunting"],
    atmosphere: ["European", "noir", "quiet", "grounded", "ominous"],
    vibes: { thriller: 10, psychological: 10, mystery: 9, action: 2, darkness: 9 },
    pacing: "patient investigative slow burn",
    complexity: 9,
    whyFansLove: ["Johan is terrifying without needing spectacle", "Tenma's morality gives the story weight", "the mystery unfolds patiently", "side characters feel human", "the dread is grounded and adult"],
    whoShouldWatch: "Viewers who want a serious, slow, psychological crime thriller with moral weight and almost no anime gimmicks.",
    whoShouldAvoid: "Skip if you need fast action, comedy relief, or flashy supernatural elements.",
    idealFollowUps: ["pluto", "death-note", "paranoia-agent", "psycho-pass", "erased"],
    joeNote: "Gold psychological anchor. Weight grounded dread, morality, investigation, and Johan-shadow tension."
  },
  {
    id: "ghost-in-the-shell-stand-alone-complex",
    titles: ["Ghost in the Shell: Stand Alone Complex"],
    aliases: ["GitS SAC", "Ghost in the Shell SAC", "Stand Alone Complex"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "cyberpunk procedural / identity philosophy",
    subdomain: "gold standard cyberpunk intelligence anchor",
    signature: "A cyberpunk police-procedural classic where networked society, identity, politics, terrorism, and machine consciousness collide through smart cases and philosophical pressure.",
    coreFantasy: "Operate at the edge of a networked future, solving crimes that force you to question where the human ends and the machine begins.",
    fantasyPillars: ["cyberbrain society", "elite tactical unit", "political conspiracy", "identity philosophy", "procedural cases", "machine consciousness"],
    emotionalJourney: ["curiosity", "cool focus", "paranoia", "awe", "ethical tension", "reflection"],
    rewardLoop: ["tech crime", "case clue", "tactical operation", "social implication", "philosophical question", "conspiracy layer"],
    dopamineSources: ["smart sci-fi ideas", "Major competence", "cyberpunk atmosphere", "procedural mysteries", "Tachikoma philosophy", "political intrigue"],
    viewerType: ["cyberpunk fan", "hard sci-fi fan", "procedural fan", "philosophy-in-anime fan"],
    viewerMotivations: ["future tech", "identity questions", "smart cases", "politics", "tactical cool"],
    themes: ["identity", "consciousness", "surveillance", "technology", "state power", "individuality"],
    emotionalProfile: ["cool", "intellectual", "melancholic", "procedural", "philosophical"],
    atmosphere: ["cyberpunk", "urban", "political", "tech-noir", "tactical"],
    vibes: { scifi: 10, cyberpunk: 10, philosophy: 9, action: 6, mystery: 8 },
    pacing: "case-based with conspiracy arc",
    complexity: 9,
    whyFansLove: ["the ideas are still sharp", "the Major is pure competence", "cases connect tech to society", "the world feels plausible", "the Tachikomas add surprising soul"],
    whoShouldWatch: "Viewers who want cyberpunk, smart sci-fi, philosophical identity questions, and tactical police cases.",
    whoShouldAvoid: "Skip if you need emotional shonen momentum or dislike talky political sci-fi.",
    idealFollowUps: ["psycho-pass", "pluto", "serial-experiments-lain", "ergo-proxy", "akira"],
    joeNote: "Gold cyberpunk anchor. Weight identity philosophy, procedural intelligence, and networked-society unease."
  },
  {
    id: "magi-the-labyrinth-of-magic",
    titles: ["Magi: The Labyrinth of Magic"],
    aliases: ["Magi", "Magi: The Kingdom of Magic"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "fantasy adventure shonen / kingdom-scale magic",
    subdomain: "gold standard colorful adventure fantasy anchor",
    signature: "A bright, magical adventure that grows from dungeon treasure hunts into kingdom politics, fate, friendship, slavery, war, and massive fantasy power.",
    coreFantasy: "Explore a colorful fantasy world of dungeons, djinn, empires, and destiny while friendships pull you through politics and impossible magical stakes.",
    fantasyPillars: ["dungeon adventure", "djinn power", "kingdom politics", "fate vs freedom", "friendship trio", "colorful world travel"],
    emotionalJourney: ["wonder", "fun", "danger", "anger", "growth", "epic scale"],
    rewardLoop: ["new land", "dungeon mystery", "magic reveal", "political tension", "friendship test", "kingdom-scale payoff"],
    dopamineSources: ["fantasy exploration", "djinn equips", "big magic", "world politics", "Aladdin/Alibaba/Morgiana chemistry", "adventure momentum"],
    viewerType: ["fantasy shonen fan", "world travel fan", "magic adventure fan", "kingdom politics fan"],
    viewerMotivations: ["adventure", "magic", "friendship", "politics", "destiny", "colorful fantasy"],
    themes: ["freedom", "fate", "friendship", "slavery", "leadership", "power"],
    emotionalProfile: ["colorful", "adventurous", "dramatic", "hopeful", "epic"],
    atmosphere: ["Arabian Nights inspired", "bright", "magical", "political", "expansive"],
    vibes: { adventure: 9, fantasy: 10, magic: 9, politics: 7, emotional: 8 },
    pacing: "adventure arcs expanding into political fantasy",
    complexity: 7,
    whyFansLove: ["the world feels colorful and adventurous", "the trio has great chemistry", "djinn powers are satisfying", "the fantasy scale keeps expanding", "the politics add weight to the adventure"],
    whoShouldWatch: "Viewers who want colorful fantasy shonen with dungeons, magic, friendship, politics, and big adventure energy.",
    whoShouldAvoid: "Skip if you dislike unfinished anime adaptations or want a fully closed ending.",
    idealFollowUps: ["one-piece", "fullmetal-alchemist-brotherhood", "black-clover", "fairy-tail", "ranking-of-kings"],
    joeNote: "Gold fantasy adventure anchor. Weight colorful world travel, dungeon fantasy, friendship trio, and kingdom politics."
  }
];
