// Gold Standard JoeAI Genome Cards - Pack 4
// Seinen / Psychological / Moral Tension Anchors
// Drop into: src/ai/genome/gold/

export const GOLD_STANDARD_GENOME_CARDS_PACK_4 = [
  {
    id: "steins-gate",
    titles: ["Steins;Gate"],
    aliases: ["Steins Gate", "Steins; Gate"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "time travel thriller / otaku tragedy",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A slow-burn time travel thriller where goofy lab-friend chaos curdles into panic, sacrifice, impossible choices, and desperate attempts to save the people you love.",
    coreFantasy: "Play with impossible science like a joke until the joke becomes fate, then fight time itself to protect the tiny found family you accidentally built.",
    fantasyPillars: ["time travel consequences", "lab found family", "otaku conspiracy", "butterfly-effect dread", "sacrifice loops", "saving one person at a cost"],
    emotionalJourney: ["goofy curiosity", "unease", "panic", "guilt", "desperation", "grief", "earned relief"],
    rewardLoop: ["lab experiment", "weird consequence", "SERN clue", "timeline shift", "personal loss", "desperate correction", "emotional breakthrough"],
    dopamineSources: ["timeline reveals", "Okabe mask slipping", "lab banter", "Mayuri stakes", "Kurisu chemistry", "conspiracy clues", "worldline payoffs"],
    viewerType: ["time-travel fan", "slow-burn thriller fan", "found-family viewer", "emotional sci-fi fan", "mystery-box enjoyer"],
    viewerMotivations: ["fixing mistakes", "saving friends", "timeline puzzle solving", "emotional payoff", "science conspiracy", "character bonds"],
    themes: ["fate", "sacrifice", "guilt", "friendship", "memory", "choice", "the cost of knowledge"],
    emotionalProfile: ["quirky", "anxious", "tragic", "intimate", "clever", "cathartic"],
    atmosphere: ["Akihabara lab", "summer paranoia", "nerdy", "claustrophobic", "increasingly tragic"],
    vibes: { sciFi: 9, mystery: 9, emotional: 9, thriller: 8, comedy: 6, romance: 7 },
    pacing: "slow setup into emotional thriller acceleration",
    complexity: 9,
    whyFansLove: ["the silly early chemistry makes later pain hit harder", "time travel rules feel emotionally consequential", "Okabe's persona becomes heartbreaking", "the mystery clicks together beautifully", "the ending feels earned"],
    whoShouldWatch: "Viewers who like slow-burn sci-fi, time loops, conspiracies, found family, and emotional payoffs that reward patience.",
    whoShouldAvoid: "Skip if you need fast action immediately or dislike heavy early banter before the plot tightens.",
    idealFollowUps: ["erased", "re-zero", "psycho-pass", "serial-experiments-lain", "summertime-rendering"],
    joeNote: "Gold anchor for emotional time-travel tension. Weight found-family cost and timeline guilt higher than generic sci-fi tags."
  },
  {
    id: "death-note",
    titles: ["Death Note"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "supernatural crime mind game",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A razor-clean cat-and-mouse thriller where a bored genius receives godlike killing power and turns justice into ego, performance, and strategic warfare.",
    coreFantasy: "Hold the power to judge the world from the shadows, then try to outthink the only detective brilliant enough to see the shape of your arrogance.",
    fantasyPillars: ["godlike notebook", "genius duel", "justice versus ego", "secret identity", "moral corruption", "investigation chess"],
    emotionalJourney: ["temptation", "confidence", "thrill", "paranoia", "control", "exposure fear", "collapse"],
    rewardLoop: ["new rule", "killer move", "detective counter", "identity trap", "public manipulation", "moral line crossed", "checkmate reversal"],
    dopamineSources: ["Light versus L deductions", "Death Note rule exploits", "dramatic reveals", "inner monologues", "trap setting", "ego-driven speeches"],
    viewerType: ["mind-game fan", "crime thriller fan", "antihero watcher", "moral debate fan", "high-concept supernatural viewer"],
    viewerMotivations: ["outsmarting opponents", "secret power fantasy", "moral tension", "identity suspense", "strategic reveals", "watching corruption"],
    themes: ["justice", "power", "ego", "surveillance", "morality", "fear", "identity"],
    emotionalProfile: ["tense", "arrogant", "theatrical", "clever", "cold", "paranoid"],
    atmosphere: ["urban", "investigative", "shadowy", "operatic", "psychological"],
    vibes: { thriller: 10, psychological: 10, supernatural: 7, dark: 8, strategy: 10 },
    pacing: "tight cat-and-mouse escalation",
    complexity: 8,
    whyFansLove: ["the premise is instantly addictive", "Light and L make every conversation a battle", "the rules create clever loopholes", "the moral argument is easy to debate", "the show feels constantly one step from exposure"],
    whoShouldWatch: "Viewers who want intense mind games, antihero corruption, supernatural crime rules, and detective-versus-killer tension.",
    whoShouldAvoid: "Skip if you need warm characters or dislike stories driven by arrogance, manipulation, and moral rot.",
    idealFollowUps: ["code-geass", "monster", "psycho-pass", "terror-in-resonance", "one-outs"],
    joeNote: "Gold anchor for mind-game anime. Weight strategic arrogance, rule exploitation, and moral corruption."
  },
  {
    id: "psycho-pass",
    titles: ["Psycho-Pass"],
    aliases: ["Psycho Pass"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "cyberpunk police philosophy thriller",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A cyberpunk crime thriller about policing a society where mental states are quantified, justice is automated, and human morality keeps breaking the system.",
    coreFantasy: "Stand inside a perfect surveillance machine and decide whether justice still means anything when the system can measure crime before choice happens.",
    fantasyPillars: ["pre-crime society", "Sibyl System", "Dominator weapons", "rookie inspector morality", "criminal philosophy", "systemic rot"],
    emotionalJourney: ["curiosity", "unease", "shock", "doubt", "moral pressure", "disillusionment", "resolve"],
    rewardLoop: ["crime scene", "psycho-pass reading", "enforcer pursuit", "philosophical villain clue", "system contradiction", "ethical choice", "larger conspiracy"],
    dopamineSources: ["Dominator judgments", "Makishima philosophy", "Akane's growth", "cyberpunk cases", "system reveals", "Kogami pursuit energy"],
    viewerType: ["cyberpunk fan", "crime procedural fan", "philosophical thriller fan", "dystopia viewer", "moral-system critic"],
    viewerMotivations: ["questioning justice", "future crime cases", "system critique", "ethical dilemmas", "cool police tech", "hunter versus monster tension"],
    themes: ["free will", "justice", "surveillance", "social control", "identity", "law", "human unpredictability"],
    emotionalProfile: ["cold", "tense", "philosophical", "violent", "clinical", "dystopian"],
    atmosphere: ["neon noir", "police procedural", "sterile future", "oppressive", "urban cyberpunk"],
    vibes: { cyberpunk: 10, thriller: 9, philosophical: 9, crime: 9, dark: 8 },
    pacing: "case-based thriller into system-level conspiracy",
    complexity: 9,
    whyFansLove: ["the world asks great moral questions", "Akane grows without losing her core", "Makishima is a strong ideological opponent", "the cases expose cracks in the system", "the cyberpunk police aesthetic hits hard"],
    whoShouldWatch: "Viewers who want cyberpunk crime, dystopian philosophy, system critique, and mature police-thriller tension.",
    whoShouldAvoid: "Skip if you dislike grim violence, dialogue-heavy philosophy, or dystopias with little comfort.",
    idealFollowUps: ["ghost-in-the-shell-sac", "monster", "death-note", "ergo-proxy", "akudama-drive"],
    joeNote: "Gold anchor for cyberpunk justice systems. Weight moral philosophy and surveillance dystopia over simple police action."
  },
  {
    id: "parasyte-the-maxim",
    titles: ["Parasyte -the maxim-"],
    aliases: ["Parasyte", "Kiseijuu", "Kiseijuu: Sei no Kakuritsu"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "body horror identity thriller",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A body-horror survival thriller where a teenager shares his body with an alien predator and slowly questions what makes humans more moral than monsters.",
    coreFantasy: "Survive becoming half-other, cooperate with the parasite inside your hand, and discover whether humanity is a feeling, a species, or a choice.",
    fantasyPillars: ["body invasion", "human/monster boundary", "forced symbiosis", "predator logic", "identity drift", "survival adaptation"],
    emotionalJourney: ["terror", "disgust", "adaptation", "loss", "numbness", "questioning", "human reconnection"],
    rewardLoop: ["parasite encounter", "Migi analysis", "body-horror fight", "human cost", "ethical question", "new predator strategy", "identity shift"],
    dopamineSources: ["Migi's cold logic", "shape-shifting fights", "Shinichi's transformation", "predator reveals", "philosophical debates", "survival tension"],
    viewerType: ["body-horror fan", "philosophical action fan", "identity-crisis viewer", "dark sci-fi fan", "monster morality fan"],
    viewerMotivations: ["survival evolution", "monster/human questions", "alien logic", "visceral fights", "psychological change", "ethical ambiguity"],
    themes: ["humanity", "predation", "identity", "grief", "environment", "symbiosis", "empathy"],
    emotionalProfile: ["creepy", "lonely", "violent", "philosophical", "tragic", "eerie"],
    atmosphere: ["ordinary life invaded", "organic horror", "alien", "paranoid", "melancholic"],
    vibes: { horror: 8, action: 8, psychological: 9, sciFi: 8, dark: 8 },
    pacing: "survival thriller into philosophical identity crisis",
    complexity: 8,
    whyFansLove: ["Migi is both funny and unsettling", "the fights are clever and brutal", "Shinichi's emotional change is disturbing", "the monster questions become surprisingly thoughtful", "it stays personal even when the stakes grow"],
    whoShouldWatch: "Viewers who like body horror, alien logic, dark action, and stories about losing and rebuilding your humanity.",
    whoShouldAvoid: "Skip if body transformation horror, gore, or emotionally cold stretches are a hard no.",
    idealFollowUps: ["tokyo-ghoul", "devilman-crybaby", "monster", "made-in-abyss", "ajin"],
    joeNote: "Gold anchor for human/monster identity. Weight symbiosis, numbness, and philosophical body horror."
  },
  {
    id: "vinland-saga",
    titles: ["Vinland Saga"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "historical revenge / anti-violence epic",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A Viking epic that begins as revenge and bloodshed before transforming into one of anime's strongest meditations on violence, slavery, masculinity, and choosing peace.",
    coreFantasy: "Chase revenge through a brutal warrior world, then face the harder dream: becoming someone who no longer needs violence to prove they exist.",
    fantasyPillars: ["Viking warfare", "revenge obsession", "father legacy", "warrior masculinity", "slavery and freedom", "true warrior ideal"],
    emotionalJourney: ["loss", "rage", "emptiness", "humiliation", "reflection", "atonement", "peaceful resolve"],
    rewardLoop: ["battlefield brutality", "political maneuver", "revenge fixation", "mentor clash", "inner emptiness", "moral awakening", "earned nonviolence"],
    dopamineSources: ["Askeladd strategy", "Viking duels", "Thorfinn growth", "historical politics", "farm arc catharsis", "true warrior philosophy"],
    viewerType: ["seinen drama fan", "historical epic fan", "character-growth viewer", "antihero recovery fan", "moral philosophy fan"],
    viewerMotivations: ["revenge consequences", "historical grit", "atonement", "masculinity questioned", "political intrigue", "earned peace"],
    themes: ["revenge", "violence", "freedom", "slavery", "fatherhood", "atonement", "what strength means"],
    emotionalProfile: ["brutal", "mournful", "reflective", "heavy", "redemptive", "human"],
    atmosphere: ["cold historical", "mud and blood", "political", "spiritual", "grounded"],
    vibes: { historical: 10, drama: 10, action: 7, philosophical: 9, emotional: 9 },
    pacing: "war revenge into slow moral rebirth",
    complexity: 9,
    whyFansLove: ["it refuses to glorify violence forever", "Askeladd is unforgettable", "Thorfinn's growth is painfully earned", "the historical world feels harsh and alive", "the message lands because the story earns it"],
    whoShouldWatch: "Viewers who want mature historical drama, brutal consequences, political tension, and one of anime's strongest redemption arcs.",
    whoShouldAvoid: "Skip if you only want constant Viking action and do not want slow introspective character work.",
    idealFollowUps: ["attack-on-titan", "kingdom", "berserk", "monster", "golden-kamuy"],
    joeNote: "Gold anchor for anti-violence seinen. Do not recommend as simple action; the transformation from revenge to peace is the core."
  },
  {
    id: "erased",
    titles: ["Erased"],
    aliases: ["Boku dake ga Inai Machi", "The Town Where Only I Am Missing"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "time-slip murder mystery / childhood rescue drama",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A compact time-slip thriller where a failed adult is thrown back into childhood and given the chance to save lonely kids before tragedy hardens into memory.",
    coreFantasy: "Return to the moment before everything went wrong, notice the lonely person everyone missed, and change the future by choosing to protect them this time.",
    fantasyPillars: ["time reversal", "childhood mystery", "rescuing the isolated", "murder prevention", "second chances", "adult regret in a child's body"],
    emotionalJourney: ["regret", "alarm", "tenderness", "suspicion", "hope", "danger", "bittersweet healing"],
    rewardLoop: ["revival jump", "childhood clue", "bond with victim", "small protection act", "killer pressure", "timeline shift", "future consequence"],
    dopamineSources: ["Kayo rescue moments", "timeline clues", "adult perspective in childhood", "winter atmosphere", "small kindness payoffs", "mystery urgency"],
    viewerType: ["compact mystery fan", "time-slip viewer", "emotional thriller fan", "protective-character enjoyer", "second-chance story fan"],
    viewerMotivations: ["saving someone", "fixing the past", "mystery solving", "childhood melancholy", "emotional healing", "small acts mattering"],
    themes: ["regret", "neglect", "protection", "friendship", "memory", "abuse", "second chances"],
    emotionalProfile: ["melancholic", "gentle", "tense", "nostalgic", "protective", "bittersweet"],
    atmosphere: ["snowy childhood", "small town", "quiet dread", "domestic sadness", "thriller pressure"],
    vibes: { mystery: 9, emotional: 9, thriller: 7, drama: 9, supernatural: 5 },
    pacing: "tight emotional mystery",
    complexity: 7,
    whyFansLove: ["the rescue fantasy is emotionally direct", "Kayo's story hits hard", "the childhood setting feels fragile", "the mystery stays focused", "small kindness becomes heroic"],
    whoShouldWatch: "Viewers who want a short emotional mystery about regret, time travel, childhood trauma, and trying to save someone who was overlooked.",
    whoShouldAvoid: "Skip if child abuse themes are too upsetting or if you need complex hard-sci-fi time travel rules.",
    idealFollowUps: ["steins-gate", "summertime-rendering", "orange", "anohana", "the-promised-neverland"],
    joeNote: "Gold anchor for emotional rescue time-slip. Weight protection and regret over supernatural mechanics."
  },
  {
    id: "made-in-abyss",
    titles: ["Made in Abyss"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "beautiful adventure horror / abyss descent",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A gorgeous and horrifying descent fantasy where childlike wonder, ancient ruins, body horror, and irreversible choices make exploration feel sacred and dangerous.",
    coreFantasy: "Descend into a beautiful forbidden world where every layer promises discovery, but curiosity costs flesh, innocence, memory, and sometimes the ability to return.",
    fantasyPillars: ["vertical lost world", "forbidden exploration", "ancient relic mystery", "curse of ascent", "childlike wonder", "beauty becoming horror"],
    emotionalJourney: ["wonder", "curiosity", "unease", "shock", "grief", "awe", "traumatized determination"],
    rewardLoop: ["new layer", "relic discovery", "creature threat", "curse consequence", "emotional bond", "horrific reveal", "descent continues"],
    dopamineSources: ["Abyss layer reveals", "creature design", "relic lore", "Nanachi moments", "beautiful music", "horror turns", "exploration stakes"],
    viewerType: ["dark fantasy fan", "worldbuilding addict", "horror-tolerant adventurer", "mystery-lore fan", "emotional trauma viewer"],
    viewerMotivations: ["forbidden discovery", "ancient mystery", "beautiful danger", "survival bonds", "irreversible stakes", "deep lore"],
    themes: ["curiosity", "sacrifice", "innocence", "obsession", "body horror", "parental absence", "the cost of wonder"],
    emotionalProfile: ["beautiful", "disturbing", "awe-filled", "cruel", "tender", "haunting"],
    atmosphere: ["storybook surface", "alien depths", "sacred ruins", "biological horror", "melancholic"],
    vibes: { adventure: 9, dark: 10, horror: 9, fantasy: 10, emotional: 9, mystery: 9 },
    pacing: "layered descent with escalating consequence",
    complexity: 9,
    whyFansLove: ["the world feels truly unknown", "beauty and horror are inseparable", "the music makes discovery feel holy", "the emotional bonds are fragile", "the Abyss itself feels like a character"],
    whoShouldWatch: "Viewers who want unforgettable dark fantasy, deep-world exploration, ancient mysteries, and emotional devastation wrapped in beauty.",
    whoShouldAvoid: "Skip if violence involving children, body horror, or extreme tonal cruelty is a dealbreaker.",
    idealFollowUps: ["dorohedoro", "shinsekai-yori", "girls-last-tour", "the-promised-neverland", "mushishi"],
    joeNote: "Gold anchor for beautiful horror adventure. Weight wonder plus irreversible trauma; never flatten it into cute adventure."
  },
  {
    id: "code-geass",
    titles: ["Code Geass"],
    aliases: ["Code Geass: Lelouch of the Rebellion"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "mecha rebellion mind-game tragedy",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A theatrical rebellion thriller where a brilliant exiled prince gains supernatural command power and tries to destroy an empire through masks, tactics, sacrifice, and ego.",
    coreFantasy: "Become the masked architect of revolution, move nations like chess pieces, and decide how much of your soul you can spend to build a better world.",
    fantasyPillars: ["masked rebellion", "Geass command power", "royal revenge", "mecha warfare", "tactical manipulation", "sacrifice for peace"],
    emotionalJourney: ["rage", "thrill", "confidence", "panic", "guilt", "isolation", "tragic grandeur"],
    rewardLoop: ["political crisis", "Zero plan", "Geass gamble", "mecha battle", "personal consequence", "public spectacle", "larger strategy revealed"],
    dopamineSources: ["Lelouch gambits", "Zero theatrics", "Geass commands", "Knightmare fights", "political betrayals", "impossible comeback plans"],
    viewerType: ["mind-game fan", "antihero strategist", "mecha drama viewer", "political rebellion fan", "tragic spectacle enjoyer"],
    viewerMotivations: ["outsmarting empires", "revenge", "masked identity", "revolution", "tactical gambits", "grand sacrifice"],
    themes: ["power", "rebellion", "identity", "sacrifice", "colonialism", "family", "ends versus means"],
    emotionalProfile: ["theatrical", "chaotic", "tragic", "brilliant", "melodramatic", "explosive"],
    atmosphere: ["imperial occupation", "school double life", "war room", "operatic", "mecha battlefield"],
    vibes: { strategy: 10, mecha: 8, drama: 9, political: 9, action: 8, psychological: 8 },
    pacing: "high-twist political/mecha escalation",
    complexity: 8,
    whyFansLove: ["Lelouch is magnetic even when reckless", "plans feel huge and theatrical", "the double life creates constant tension", "the show commits to big twists", "the ending gives the chaos a mythic shape"],
    whoShouldWatch: "Viewers who want strategic antihero drama, rebellion politics, mecha battles, identity games, and huge emotional swings.",
    whoShouldAvoid: "Skip if you dislike melodrama, contrivance, or protagonists who manipulate everyone around them.",
    idealFollowUps: ["death-note", "gundam-00", "86", "legend-of-the-galactic-heroes", "attack-on-titan"],
    joeNote: "Gold anchor for theatrical strategy. Weight masked revolution, tactics, and sacrificial antiheroism over generic mecha."
  },
  {
    id: "cyberpunk-edgerunners",
    titles: ["Cyberpunk: Edgerunners"],
    aliases: ["Cyberpunk Edgerunners"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "neon tragedy / cyberpunk crew burnout",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A short, explosive cyberpunk tragedy about found-family criminals, body modification addiction, doomed love, and burning bright in a city designed to eat you.",
    coreFantasy: "Join the night-city outcasts, chrome yourself into something stronger, fall in love under neon, and realize too late that the city never lets dreamers leave clean.",
    fantasyPillars: ["Night City survival", "crew found family", "cyberware escalation", "doomed romance", "capitalist meat grinder", "burnout glory"],
    emotionalJourney: ["loss", "rush", "belonging", "love", "overconfidence", "collapse", "devastation"],
    rewardLoop: ["street job", "crew bonding", "chrome upgrade", "bigger score", "romantic dream", "body cost", "violent consequence"],
    dopamineSources: ["neon action", "Rebecca chaos", "David power jumps", "Lucy dream scenes", "crew vibes", "music drops", "tragic momentum"],
    viewerType: ["cyberpunk fan", "short emotional gut-punch viewer", "found-family crime fan", "doomed romance enjoyer", "stylish action fan"],
    viewerMotivations: ["outsider belonging", "power escalation", "anti-corporate rage", "romantic escape", "crew loyalty", "tragic beauty"],
    themes: ["exploitation", "identity", "ambition", "love", "addiction", "class", "self-destruction"],
    emotionalProfile: ["neon", "furious", "romantic", "reckless", "tragic", "stylish"],
    atmosphere: ["neon city", "corporate dystopia", "street crime", "body-tech nightmare", "music-video kinetic"],
    vibes: { cyberpunk: 10, action: 9, emotional: 9, tragedy: 10, style: 10, romance: 7 },
    pacing: "fast doomed escalation",
    complexity: 7,
    whyFansLove: ["it wastes no time", "the crew feels alive fast", "the action and music hit hard", "David's rise feels addictive and terrifying", "the ending leaves a bruise"],
    whoShouldWatch: "Viewers who want a compact cyberpunk gut-punch with found family, neon violence, doomed romance, and no safe landing.",
    whoShouldAvoid: "Skip if you hate tragic endings, extreme violence, or stories where systems crush nearly everyone.",
    idealFollowUps: ["akudama-drive", "psycho-pass", "ghost-in-the-shell-sac", "akira", "redline"],
    joeNote: "Gold anchor for short-form cyberpunk tragedy. Weight crew warmth plus self-destruction; do not treat it as just game tie-in action."
  },
  {
    id: "akudama-drive",
    titles: ["Akudama Drive"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "cyberpunk criminal sprint / identity chaos",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A hyper-stylized cyberpunk crime sprint where disposable criminals, false identities, class violence, and impossible momentum turn a simple delivery job into rebellion by accident.",
    coreFantasy: "Get mistaken for someone dangerous, run with legendary criminals through a neon police state, and become real through the role you were never supposed to survive.",
    fantasyPillars: ["criminal ensemble", "false identity", "neon police state", "impossible delivery", "class execution system", "style-overload momentum"],
    emotionalJourney: ["confusion", "thrill", "panic", "attachment", "defiance", "sacrifice", "mythic exit"],
    rewardLoop: ["new objective", "criminal specialty", "executioner pursuit", "over-the-top escape", "system cruelty reveal", "identity hardens", "sacrifice move"],
    dopamineSources: ["criminal codenames", "neon chase scenes", "Brawler fights", "Swindler growth", "Executioner duels", "stylized violence", "momentum twists"],
    viewerType: ["style-first action fan", "cyberpunk chaos fan", "criminal ensemble enjoyer", "short series binge viewer", "anti-system viewer"],
    viewerMotivations: ["criminal cool factor", "fast pacing", "identity reinvention", "neon spectacle", "anti-authority chaos", "survival through performance"],
    themes: ["identity", "class", "state violence", "performance", "sacrifice", "media spectacle", "criminal myth"],
    emotionalProfile: ["loud", "neon", "violent", "chaotic", "cool", "surprisingly sincere"],
    atmosphere: ["hyper-neon", "police-state", "arcade cyberpunk", "criminal underground", "runaway train"],
    vibes: { cyberpunk: 9, action: 10, style: 10, chaos: 10, darkComedy: 7, thriller: 8 },
    pacing: "full-throttle mission sprint",
    complexity: 7,
    whyFansLove: ["it moves like a bullet train", "every character has instant visual identity", "the world is stylish and cruel", "Swindler's arc sneaks up emotionally", "the show knows exactly when to go huge"],
    whoShouldWatch: "Viewers who want short, stylish cyberpunk action with criminal chaos, neon momentum, and a surprisingly strong identity arc.",
    whoShouldAvoid: "Skip if you need quiet realism, long character backstories, or subtle pacing.",
    idealFollowUps: ["cyberpunk-edgerunners", "dorohedoro", "redline", "psycho-pass", "kill-la-kill"],
    joeNote: "Gold anchor for stylish criminal sprint anime. Weight momentum, identity performance, and neon chaos."
  }
];

export default GOLD_STANDARD_GENOME_CARDS_PACK_4;
