// Gold Standard JoeAI Genome Cards - Pack 6
// Flagship discovery anchors selected for new-user coverage and routing tests.

function goldCard({
  id,
  titles,
  aliases = [],
  domain,
  signature,
  coreFantasy,
  pillars,
  motivations,
  themes,
  emotions,
  atmosphere,
  vibes,
  pacing,
  complexity = 7,
  followUps,
  avoid
}) {
  const emotionalJourney = emotions.slice(0, 6);
  const rewardLoop = pillars.slice(0, 6);

  return {
    id,
    titles,
    aliases,
    quality: 'gold',
    generationQuality: 'curated',
    confidence: 0.98,
    generated: false,
    needsReview: false,
    domain,
    subdomain: 'gold standard audience-fantasy profile',
    signature,
    description: signature,
    coreFantasy,
    fantasyPillars: pillars,
    emotionalJourney,
    rewardLoop,
    dopamineSources: [...pillars.slice(0, 3), ...motivations.slice(0, 3)],
    viewerType: motivations.map((motivation) => `${motivation} viewer`).slice(0, 4),
    viewerMotivations: motivations,
    whyPick: motivations,
    bestFor: `Viewers looking for ${motivations.slice(0, 3).join(', ')}.`,
    themes,
    emotionalProfile: emotions,
    atmosphere,
    vibes,
    pacing,
    complexity,
    whyFansLove: [signature, ...pillars.slice(0, 4)],
    whoShouldWatch: `Watch when you want ${motivations.slice(0, 4).join(', ')}.`,
    whoShouldAvoid: avoid,
    idealFollowUps: followUps,
    nearbyPicks: followUps,
    joeNote: `Gold anchor for ${domain}. Weight the experience profile over surface genre overlap.`
  };
}

export const GOLD_STANDARD_GENOME_CARDS_PACK_6 = [
  goldCard({
    id: 'cowboy-bebop',
    titles: ['Cowboy Bebop'],
    domain: 'melancholic space western',
    signature: 'A stylish bounty-hunting road show where cool surfaces hide loneliness, unfinished histories, and people who cannot outrun the past.',
    coreFantasy: 'Drift through the solar system with a damaged found family, taking strange jobs while old lives keep catching up.',
    pillars: ['episodic bounty hunts', 'found-family chemistry', 'jazz cool', 'adult melancholy', 'genre hopping'],
    motivations: ['stylish science fiction', 'adult character drama', 'episodic variety', 'bittersweet atmosphere'],
    themes: ['the past', 'identity', 'loneliness', 'freedom', 'found family'],
    emotions: ['cool', 'wistful', 'funny', 'lonely', 'bittersweet'],
    atmosphere: ['lived-in spaceships', 'jazz clubs', 'dusty colonies', 'noir cities'],
    vibes: { scifi: 9, action: 7, emotional: 8, comedy: 5, mystery: 5 },
    pacing: 'episodic adventures with slow-burn character revelations',
    followUps: ['samurai-champloo', 'space-dandy', 'trigun', 'ghost-in-the-shell-stand-alone-complex'],
    avoid: 'Skip if you need a tightly serialized plot or constant lore progression.'
  }),
  goldCard({
    id: 'neon-genesis-evangelion',
    titles: ['Neon Genesis Evangelion'],
    aliases: ['Evangelion', 'NGE'],
    domain: 'psychological apocalyptic mecha',
    signature: 'A monster-defense mecha story that folds inward into fear, depression, intimacy, parental damage, and the terror of being known.',
    coreFantasy: 'Pilot an impossible machine to save the world while confronting the emotional wounds that make connection feel dangerous.',
    pillars: ['apocalyptic battles', 'psychological collapse', 'symbolic mystery', 'damaged pilots', 'existential introspection'],
    motivations: ['psychological depth', 'mecha spectacle', 'symbolic mystery', 'challenging character study'],
    themes: ['connection', 'self-worth', 'depression', 'identity', 'parental trauma'],
    emotions: ['anxious', 'alienated', 'intimate', 'terrifying', 'cathartic'],
    atmosphere: ['submerged fortress city', 'clinical command rooms', 'biblical apocalypse', 'interior mindscapes'],
    vibes: { psychological: 10, scifi: 9, dark: 9, action: 7, emotional: 10 },
    pacing: 'monster-of-the-week pressure that becomes inward and abstract',
    complexity: 10,
    followUps: ['code-geass', 'psycho-pass', 'pluto', 'serial-experiments-lain'],
    avoid: 'Skip if ambiguity, abstraction, or emotionally distressed characters are a hard no.'
  }),
  goldCard({
    id: 'mob-psycho-100',
    titles: ['Mob Psycho 100'],
    aliases: ['Mob Psycho'],
    domain: 'psychic coming-of-age comedy',
    signature: 'An explosive psychic action comedy whose real power fantasy is learning emotional honesty, kindness, boundaries, and ordinary self-confidence.',
    coreFantasy: 'Possess overwhelming supernatural power but discover that becoming a good, complete person matters more than winning fights.',
    pillars: ['psychic spectacle', 'earnest self-improvement', 'absurd comedy', 'mentor bond', 'emotional breakthroughs'],
    motivations: ['character growth', 'inventive action', 'heartfelt comedy', 'healthy self-worth'],
    themes: ['identity', 'kindness', 'growth', 'power', 'emotional honesty'],
    emotions: ['funny', 'warm', 'kinetic', 'earnest', 'uplifting'],
    atmosphere: ['ordinary schools', 'spirit offices', 'surreal psychic storms', 'quiet neighborhoods'],
    vibes: { action: 9, comedy: 8, wholesome: 9, emotional: 8, chaos: 7 },
    pacing: 'fast comedy and action anchored by steady personal growth',
    followUps: ['one-punch-man', 'dandadan', 'spy-x-family', 'saiki-k'],
    avoid: 'Skip if deliberately loose art or broad comedy prevents you from engaging.'
  }),
  goldCard({
    id: 'kaguya-sama-love-is-war',
    titles: ['Kaguya-sama: Love Is War'],
    aliases: ['Kaguya-sama', 'Love Is War'],
    domain: 'romantic mind-game comedy',
    signature: 'Two brilliant teenagers turn mutual attraction into an escalating psychological war because admitting love feels more dangerous than any defeat.',
    coreFantasy: 'Experience first love as elaborate strategy, social disaster, ensemble comedy, and eventually sincere emotional vulnerability.',
    pillars: ['romantic mind games', 'ensemble chemistry', 'narrator comedy', 'slow confession', 'emotional payoff'],
    motivations: ['romantic comedy', 'clever banter', 'slow-burn payoff', 'lovable ensemble'],
    themes: ['pride', 'vulnerability', 'friendship', 'love', 'class'],
    emotions: ['hilarious', 'romantic', 'anxious', 'sweet', 'cathartic'],
    atmosphere: ['elite academy', 'student council room', 'festival nights', 'awkward dates'],
    vibes: { comedy: 10, romance: 10, psychological: 7, wholesome: 8, emotional: 7 },
    pacing: 'sketch-like battles that accumulate into major romantic arcs',
    followUps: ['bocchi-the-rock', 'horimiya', 'monthly-girls-nozaki-kun', 'spy-x-family'],
    avoid: 'Skip if slow romantic progress or exaggerated internal monologues frustrate you.'
  }),
  goldCard({
    id: 'haikyu',
    titles: ['Haikyu!!'],
    aliases: ['Haikyuu', 'Haikyuu!!'],
    domain: 'team-sports mastery journey',
    signature: 'A volleyball growth story where every rotation turns technique, rivalry, teamwork, and tiny personal breakthroughs into enormous emotional wins.',
    coreFantasy: 'Join an underdog team, sharpen one skill at a time, and discover that rivals can become the people who reveal your best self.',
    pillars: ['team chemistry', 'skill progression', 'rivalry respect', 'match tension', 'earned confidence'],
    motivations: ['sports excitement', 'underdog growth', 'ensemble attachment', 'earned victories'],
    themes: ['teamwork', 'ambition', 'failure', 'practice', 'rivalry'],
    emotions: ['energizing', 'hopeful', 'tense', 'joyful', 'inspiring'],
    atmosphere: ['school gyms', 'training camps', 'packed tournaments', 'quiet practice courts'],
    vibes: { mastery: 10, wholesome: 9, emotional: 8, action: 7, comedy: 6 },
    pacing: 'training and character arcs that peak in detailed matches',
    followUps: ['run-with-the-wind', 'blue-lock', 'hajime-no-ippo', 'slam-dunk'],
    avoid: 'Skip if realistic sports technique and long matches do not interest you.'
  }),
  goldCard({
    id: 'spy-x-family',
    titles: ['SPY x FAMILY'],
    aliases: ['Spy Family', 'Spy x Family'],
    domain: 'found-family spy comedy',
    signature: 'A fake family made of a spy, an assassin, and a telepath accidentally becomes emotionally real through missions, school chaos, and domestic tenderness.',
    coreFantasy: 'Build the strangest secret household imaginable and watch performance turn into genuine belonging.',
    pillars: ['secret identities', 'found family', 'mission comedy', 'child perspective', 'domestic warmth'],
    motivations: ['wholesome comedy', 'family attachment', 'light action', 'secret-identity hijinks'],
    themes: ['family', 'belonging', 'peace', 'deception', 'childhood'],
    emotions: ['warm', 'funny', 'playful', 'suspenseful', 'tender'],
    atmosphere: ['cold-war city', 'cozy apartment', 'elite academy', 'stylish missions'],
    vibes: { wholesome: 10, comedy: 9, action: 6, mystery: 5, emotional: 7 },
    pacing: 'episodic family comedy with recurring mission and school arcs',
    followUps: ['mob-psycho-100', 'kaguya-sama-love-is-war', 'buddy-daddies', 'the-apothecary-diaries'],
    avoid: 'Skip if you need constant plot advancement or serious espionage realism.'
  }),
  goldCard({
    id: 'chainsaw-man',
    titles: ['Chainsaw Man'],
    domain: 'feral supernatural tragedy',
    signature: 'A brutally funny devil-hunting story about poverty, appetite, manipulation, intimacy, and a boy whose smallest dreams become weapons against him.',
    coreFantasy: 'Gain monstrous power and chase an ordinary good life while predatory adults reshape every desire you have.',
    pillars: ['visceral devil fights', 'black comedy', 'damaged intimacy', 'cinematic direction', 'sudden tragedy'],
    motivations: ['violent action', 'unpredictable storytelling', 'dark humor', 'emotionally damaged characters'],
    themes: ['desire', 'control', 'poverty', 'intimacy', 'humanity'],
    emotions: ['feral', 'funny', 'lonely', 'shocking', 'tragic'],
    atmosphere: ['grimy apartments', 'bureaucratic devil hunting', 'rain-soaked cities', 'nightmare spaces'],
    vibes: { dark: 10, action: 9, horror: 9, comedy: 7, emotional: 8 },
    pacing: 'lean escalation with abrupt tonal and emotional reversals',
    followUps: ['dorohedoro', 'hells-paradise', 'jujutsu-kaisen', 'cyberpunk-edgerunners'],
    avoid: 'Skip if gore, sexual manipulation, or abrupt cruelty are dealbreakers.'
  }),
  goldCard({
    id: 'dr-stone',
    titles: ['Dr. STONE'],
    aliases: ['Dr Stone'],
    domain: 'science civilization adventure',
    signature: 'A post-apocalyptic adventure that turns chemistry, engineering, teamwork, and incremental invention into the power-progression system.',
    coreFantasy: 'Rebuild civilization from nothing using knowledge, experiments, and a growing village of specialists.',
    pillars: ['science progression', 'civilization building', 'invention payoffs', 'team specialization', 'adventure puzzles'],
    motivations: ['clever problem solving', 'kingdom building', 'optimistic adventure', 'visible progression'],
    themes: ['knowledge', 'cooperation', 'civilization', 'curiosity', 'legacy'],
    emotions: ['optimistic', 'curious', 'exciting', 'funny', 'triumphant'],
    atmosphere: ['stone world wilderness', 'maker workshop', 'primitive villages', 'expeditions'],
    vibes: { scifi: 9, adventure: 9, mastery: 9, wholesome: 7, comedy: 6 },
    pacing: 'invention arcs with clear goals and compounding rewards',
    followUps: ['log-horizon', 'that-time-i-got-reincarnated-as-a-slime', 'delicious-in-dungeon', 'ascendance-of-a-bookworm'],
    avoid: 'Skip if exaggerated science explanations or broad comedy pull you out.'
  }),
  goldCard({
    id: 'samurai-champloo',
    titles: ['Samurai Champloo'],
    domain: 'hip-hop samurai road story',
    signature: 'A loose, stylish journey across Edo Japan where clashing fighters, music, comedy, and buried grief create a fiercely modern historical adventure.',
    coreFantasy: 'Cross Japan with two incompatible swordsmen and find freedom, identity, and friendship between episodic detours.',
    pillars: ['road-trip structure', 'kinetic sword fights', 'hip-hop identity', 'trio chemistry', 'historical remix'],
    motivations: ['stylish action', 'episodic adventure', 'music-driven atmosphere', 'unlikely friendship'],
    themes: ['freedom', 'identity', 'friendship', 'history', 'survival'],
    emotions: ['cool', 'funny', 'restless', 'wistful', 'bittersweet'],
    atmosphere: ['Edo backroads', 'street culture', 'seaside towns', 'moonlit duels'],
    vibes: { action: 9, adventure: 8, comedy: 6, emotional: 7, chaos: 6 },
    pacing: 'episodic road adventures with a focused closing journey',
    followUps: ['cowboy-bebop', 'space-dandy', 'dororo', 'afro-samurai'],
    avoid: 'Skip if you require continuous plot momentum in every episode.'
  }),
  goldCard({
    id: 'trigun',
    titles: ['Trigun'],
    domain: 'pacifist gunslinger western',
    signature: 'A seemingly goofy wasteland gunslinger story that slowly exposes the unbearable cost of pacifism, reputation, and refusing to kill.',
    coreFantasy: 'Be the legendary outlaw who can survive anything without surrendering compassion, even when the world punishes mercy.',
    pillars: ['pacifist hero', 'desert western', 'comic misdirection', 'moral tests', 'tragic history'],
    motivations: ['charismatic hero', 'moral conflict', 'western adventure', 'tone that deepens'],
    themes: ['pacifism', 'mercy', 'responsibility', 'trauma', 'brotherhood'],
    emotions: ['goofy', 'adventurous', 'lonely', 'earnest', 'tragic'],
    atmosphere: ['desert planets', 'frontier towns', 'dusty saloons', 'ruined technology'],
    vibes: { action: 8, comedy: 6, emotional: 8, scifi: 7, adventure: 8 },
    pacing: 'comic episodic western that reveals a serious central conflict',
    followUps: ['cowboy-bebop', 'samurai-champloo', 'space-dandy', 'desert-punk'],
    avoid: 'Skip if older animation or an initially goofy lead stops you early.'
  }),
  goldCard({
    id: 'violet-evergarden',
    titles: ['Violet Evergarden'],
    domain: 'healing postwar letter drama',
    signature: 'A former child soldier learns the language of emotion by writing letters for strangers whose grief, love, and memory mirror her own.',
    coreFantasy: 'Travel through other people’s lives and slowly translate trauma into empathy, language, and the ability to love.',
    pillars: ['episodic human stories', 'postwar healing', 'letter writing', 'visual beauty', 'emotional catharsis'],
    motivations: ['beautiful drama', 'healing journey', 'episodic emotion', 'quiet character growth'],
    themes: ['grief', 'love', 'language', 'war', 'healing'],
    emotions: ['elegant', 'sad', 'tender', 'reflective', 'cathartic'],
    atmosphere: ['European-inspired cities', 'quiet writing rooms', 'war-scarred countryside', 'seasonal landscapes'],
    vibes: { emotional: 10, wholesome: 7, romance: 6, dark: 4, mystery: 3 },
    pacing: 'patient episodic stories that accumulate into personal healing',
    followUps: ['a-silent-voice', 'your-lie-in-april', 'frieren-beyond-journeys-end', 'march-comes-in-like-a-lion'],
    avoid: 'Skip if deliberate sentimentality or slow episodic drama does not work for you.'
  }),
  goldCard({
    id: 'your-lie-in-april',
    titles: ['Your Lie in April'],
    aliases: ['Shigatsu wa Kimi no Uso'],
    domain: 'musical first-love tragedy',
    signature: 'A traumatized pianist is pulled back toward music and life by a radiant violinist whose urgency hides a devastating truth.',
    coreFantasy: 'Be awakened from grief by art, friendship, and first love, even knowing beauty cannot always stay.',
    pillars: ['music performance', 'trauma recovery', 'first love', 'youth ensemble', 'tragic revelation'],
    motivations: ['emotional romance', 'music drama', 'cathartic sadness', 'coming-of-age healing'],
    themes: ['grief', 'art', 'love', 'memory', 'courage'],
    emotions: ['romantic', 'hopeful', 'anxious', 'heartbreaking', 'cathartic'],
    atmosphere: ['concert halls', 'spring parks', 'school music rooms', 'hospital corridors'],
    vibes: { emotional: 10, romance: 9, wholesome: 5, mastery: 6, dark: 5 },
    pacing: 'performance arcs and memory triggers building toward tragedy',
    followUps: ['violet-evergarden', 'a-silent-voice', 'anohana', 'nana'],
    avoid: 'Skip if melodrama, illness stories, or extended grief are too heavy.'
  }),
  goldCard({
    id: 'a-silent-voice',
    titles: ['A Silent Voice'],
    aliases: ['Koe no Katachi', 'The Shape of Voice'],
    domain: 'redemptive social drama film',
    signature: 'A former bully tries to reconnect with the deaf girl he hurt, confronting shame, isolation, depression, and the difficult work of repair.',
    coreFantasy: 'Return to the harm you caused and discover whether apology, accountability, and human connection can make life possible again.',
    pillars: ['redemption', 'social isolation', 'disability perspective', 'visual subjectivity', 'earned connection'],
    motivations: ['serious character drama', 'redemption story', 'emotional film', 'empathetic perspective'],
    themes: ['bullying', 'forgiveness', 'suicide', 'communication', 'self-worth'],
    emotions: ['painful', 'intimate', 'anxious', 'hopeful', 'cathartic'],
    atmosphere: ['school corridors', 'riverside walks', 'quiet bedrooms', 'summer festival'],
    vibes: { emotional: 10, romance: 5, dark: 7, wholesome: 5, psychological: 7 },
    pacing: 'compressed film drama focused on interior change and relationships',
    followUps: ['violet-evergarden', 'your-lie-in-april', 'march-comes-in-like-a-lion', 'orange'],
    avoid: 'Skip if bullying, suicide, or social anxiety themes are unsafe for you.'
  }),
  goldCard({
    id: 'your-name',
    titles: ['Your Name.'],
    aliases: ['Your Name', 'Kimi no Na wa'],
    domain: 'romantic body-swap time mystery film',
    signature: 'A playful body-swap romance widens into a longing-filled mystery about memory, disaster, distance, and reaching someone across time.',
    coreFantasy: 'Fall in love through another person’s life and fight time itself to keep a connection neither of you can fully remember.',
    pillars: ['body-swap intimacy', 'time mystery', 'romantic longing', 'disaster stakes', 'visual wonder'],
    motivations: ['romantic fantasy', 'emotional mystery', 'beautiful film', 'high-concept connection'],
    themes: ['memory', 'fate', 'connection', 'identity', 'loss'],
    emotions: ['playful', 'romantic', 'mysterious', 'urgent', 'uplifting'],
    atmosphere: ['rural mountain town', 'Tokyo commutes', 'twilight skies', 'comet-lit night'],
    vibes: { romance: 10, emotional: 9, mystery: 8, fantasy: 8, wholesome: 6 },
    pacing: 'light romantic setup that pivots into a race against time',
    followUps: ['weathering-with-you', 'a-silent-voice', 'suzume', 'the-girl-who-leapt-through-time'],
    avoid: 'Skip if coincidence-heavy romance or sentimental spectacle is not your thing.'
  }),
  goldCard({
    id: 'bocchi-the-rock',
    titles: ['Bocchi the Rock!'],
    aliases: ['Bocchi the Rock'],
    domain: 'social-anxiety band comedy',
    signature: 'A painfully shy guitarist joins a band and turns social panic into visual comedy, tiny acts of courage, and genuine creative belonging.',
    coreFantasy: 'Find your people through music even when every ordinary conversation feels like a boss fight.',
    pillars: ['social-anxiety comedy', 'band chemistry', 'creative experimentation', 'small victories', 'live performance'],
    motivations: ['inventive comedy', 'relatable anxiety', 'music friendship', 'gentle growth'],
    themes: ['anxiety', 'friendship', 'creativity', 'belonging', 'self-expression'],
    emotions: ['hilarious', 'awkward', 'warm', 'energizing', 'hopeful'],
    atmosphere: ['tiny live house', 'bedroom practice', 'school hallways', 'city music shops'],
    vibes: { comedy: 10, wholesome: 9, emotional: 7, mastery: 6, chaos: 8 },
    pacing: 'compact comedy episodes with accumulating band milestones',
    followUps: ['kaguya-sama-love-is-war', 'k-on', 'skip-and-loafer', 'nichijou'],
    avoid: 'Skip if extreme reaction comedy or slice-of-life pacing does not land.'
  }),
  goldCard({
    id: 'delicious-in-dungeon',
    titles: ['Delicious in Dungeon'],
    aliases: ['Dungeon Meshi'],
    domain: 'culinary dungeon ecology adventure',
    signature: 'A rescue quest becomes a joyful study of monster cooking, dungeon ecology, party dysfunction, grief, and the ethics of appetite.',
    coreFantasy: 'Explore a living dungeon with practical adventurers who survive by understanding and eating the world around them.',
    pillars: ['monster cuisine', 'dungeon ecology', 'party chemistry', 'rescue quest', 'worldbuilding payoff'],
    motivations: ['creative fantasy worldbuilding', 'food adventure', 'ensemble comedy', 'story that deepens'],
    themes: ['appetite', 'death', 'ecology', 'companionship', 'acceptance'],
    emotions: ['cozy', 'curious', 'funny', 'unsettling', 'heartfelt'],
    atmosphere: ['ancient dungeon floors', 'campfire kitchens', 'monster habitats', 'buried kingdoms'],
    vibes: { fantasy: 10, adventure: 9, comedy: 8, cozy: 8, dark: 5 },
    pacing: 'episodic meals that steadily reveal a larger dungeon narrative',
    followUps: ['frieren-beyond-journeys-end', 'dr-stone', 'made-in-abyss', 'golden-kamuy'],
    avoid: 'Skip if food focus or methodical dungeon exploration sounds tedious.'
  }),
  goldCard({
    id: 'the-apothecary-diaries',
    titles: ['The Apothecary Diaries'],
    aliases: ['Kusuriya no Hitorigoto', 'Apothecary Diaries'],
    domain: 'palace medical mystery',
    signature: 'A poison-obsessed apothecary solves intimate court mysteries while navigating class, medicine, politics, and unwanted attention with dry intelligence.',
    coreFantasy: 'Use specialized knowledge to see through palace secrets while remaining stubbornly yourself inside a dangerous hierarchy.',
    pillars: ['medical mysteries', 'sharp heroine', 'court intrigue', 'slow romance', 'observational deduction'],
    motivations: ['clever mystery solving', 'competent heroine', 'historical atmosphere', 'slow-burn chemistry'],
    themes: ['knowledge', 'class', 'gender', 'survival', 'curiosity'],
    emotions: ['witty', 'intriguing', 'elegant', 'tense', 'romantic'],
    atmosphere: ['imperial rear palace', 'medicine rooms', 'banquet halls', 'night gardens'],
    vibes: { mystery: 10, psychological: 7, romance: 6, comedy: 5, mastery: 8 },
    pacing: 'case-based mysteries that accumulate court and character threads',
    followUps: ['odd-taxi', 'spy-x-family', 'raven-of-the-inner-palace', 'ascendance-of-a-bookworm'],
    avoid: 'Skip if dialogue-heavy mysteries and gradual romance feel too restrained.'
  }),
  goldCard({
    id: 'odd-taxi',
    titles: ['ODDTAXI'],
    aliases: ['Odd Taxi'],
    domain: 'urban ensemble mystery',
    signature: 'A quiet taxi driver becomes the hub of a tightly wound city mystery where ordinary conversations, eccentric passengers, and hidden perception all matter.',
    coreFantasy: 'Observe a whole city from one cab and slowly realize every casual encounter belongs to the same dangerous puzzle.',
    pillars: ['interlocking ensemble', 'natural dialogue', 'crime mystery', 'visual misdirection', 'precise payoff'],
    motivations: ['tight mystery construction', 'adult dialogue', 'ensemble puzzle', 'unexpected reveals'],
    themes: ['perception', 'loneliness', 'fame', 'crime', 'connection'],
    emotions: ['dry', 'curious', 'uneasy', 'tense', 'satisfying'],
    atmosphere: ['late-night Tokyo', 'taxi interiors', 'small clubs', 'anonymous apartments'],
    vibes: { mystery: 10, psychological: 8, comedy: 5, dark: 6, emotional: 6 },
    pacing: 'dense conversations and parallel threads with a strong convergence',
    complexity: 9,
    followUps: ['the-apothecary-diaries', 'monster', 'erased', 'baccano'],
    avoid: 'Skip if anthropomorphic character designs or talk-heavy plotting turn you away.'
  }),
  goldCard({
    id: 'pluto',
    titles: ['PLUTO'],
    aliases: ['Pluto'],
    domain: 'humanist robot murder mystery',
    signature: 'A detective hunts a killer targeting the world’s greatest robots while war trauma, artificial emotion, prejudice, and grief complicate every answer.',
    coreFantasy: 'Investigate impossible murders in a future where machines may be more humane than the people who built them.',
    pillars: ['murder investigation', 'robot personhood', 'war trauma', 'adult science fiction', 'moral grief'],
    motivations: ['serious science fiction', 'detective mystery', 'humanist themes', 'mature drama'],
    themes: ['humanity', 'war', 'hatred', 'memory', 'grief'],
    emotions: ['somber', 'mysterious', 'compassionate', 'tense', 'tragic'],
    atmosphere: ['future Europe', 'robot homes', 'rainy investigations', 'war ruins'],
    vibes: { scifi: 10, mystery: 9, psychological: 8, emotional: 9, dark: 7 },
    pacing: 'patient prestige mystery with intersecting character tragedies',
    complexity: 9,
    followUps: ['monster', 'psycho-pass', 'ghost-in-the-shell-stand-alone-complex', 'neon-genesis-evangelion'],
    avoid: 'Skip if slow adult drama or war-trauma themes are not what you want.'
  }),
  goldCard({
    id: 'heavenly-delusion',
    titles: ['Heavenly Delusion'],
    aliases: ['Tengoku Daimakyo'],
    domain: 'post-apocalyptic dual mystery',
    signature: 'Two intercut journeys through a ruined Japan and an isolated academy build a disturbing puzzle about bodies, identity, monsters, and manufactured safety.',
    coreFantasy: 'Cross a beautiful dead world with someone you trust while uncovering how your journey connects to a sealed community’s secrets.',
    pillars: ['dual timelines', 'ruined-world travel', 'body mystery', 'companion chemistry', 'horror revelations'],
    motivations: ['post-apocalyptic mystery', 'atmospheric travel', 'character chemistry', 'slow revelations'],
    themes: ['identity', 'bodies', 'trust', 'memory', 'experimentation'],
    emotions: ['curious', 'warm', 'uneasy', 'shocking', 'melancholic'],
    atmosphere: ['overgrown cities', 'abandoned facilities', 'sealed school', 'quiet roads'],
    vibes: { mystery: 10, scifi: 8, horror: 8, adventure: 8, emotional: 7 },
    pacing: 'travel episodes and parallel clues with delayed answers',
    complexity: 9,
    followUps: ['made-in-abyss', 'summertime-rendering', 'erased', 'the-promised-neverland'],
    avoid: 'Skip if sexual violence, body horror, or unresolved mysteries are dealbreakers.'
  }),
  goldCard({
    id: 'summertime-rendering',
    titles: ['Summer Time Rendering'],
    aliases: ['Summertime Rendering', 'Summer Time Render'],
    domain: 'island time-loop thriller',
    signature: 'A funeral homecoming becomes a lethal island conspiracy where time loops reward observation, tactical adaptation, and emotional resolve.',
    coreFantasy: 'Replay a closed-island nightmare until you understand the enemy well enough to save everyone without losing yourself.',
    pillars: ['time-loop tactics', 'island mystery', 'body doubles', 'escalating rules', 'romantic urgency'],
    motivations: ['fast mystery payoff', 'time-loop strategy', 'supernatural thriller', 'complete story'],
    themes: ['memory', 'identity', 'grief', 'sacrifice', 'home'],
    emotions: ['tense', 'mysterious', 'urgent', 'romantic', 'cathartic'],
    atmosphere: ['summer island', 'empty shrines', 'coastal caves', 'festival night'],
    vibes: { mystery: 10, psychological: 8, horror: 8, action: 8, romance: 5 },
    pacing: 'rapid loop escalation with frequent answers and counterplay',
    followUps: ['steins-gate', 'rezero-starting-life-in-another-world', 'erased', 'heavenly-delusion'],
    avoid: 'Skip if repeated timelines, violence, or dense supernatural rules overwhelm you.'
  }),
  goldCard({
    id: 'ranking-of-kings',
    titles: ['Ranking of Kings'],
    aliases: ['Ousama Ranking'],
    domain: 'storybook courage fantasy',
    signature: 'A tiny deaf prince dismissed as powerless begins a fairy-tale journey where courage, betrayal, compassion, and complicated loyalties redefine strength.',
    coreFantasy: 'Prove that empathy and persistence can make a worthy king even when everyone mistakes gentleness for weakness.',
    pillars: ['underdog prince', 'storybook world', 'moral reversals', 'friendship bond', 'earned courage'],
    motivations: ['heartfelt fantasy', 'underdog growth', 'complex loyalties', 'fairy-tale adventure'],
    themes: ['courage', 'leadership', 'disability', 'family', 'forgiveness'],
    emotions: ['tender', 'hopeful', 'painful', 'adventurous', 'uplifting'],
    atmosphere: ['storybook kingdoms', 'shadow clans', 'underworld trials', 'royal courts'],
    vibes: { fantasy: 9, wholesome: 8, emotional: 9, adventure: 8, dark: 5 },
    pacing: 'fast fairy-tale arcs with frequent perspective reversals',
    followUps: ['frieren-beyond-journeys-end', 'mob-psycho-100', 'the-faraway-paladin', 'made-in-abyss'],
    avoid: 'Skip if the storybook visual style keeps you from taking drama seriously.'
  }),
  goldCard({
    id: 'konosuba',
    titles: ["KONOSUBA -God's blessing on this wonderful world!"],
    aliases: ['KonoSuba', 'Konosuba'],
    domain: 'disaster-party isekai comedy',
    signature: 'An isekai adventuring party made entirely of talented disasters turns quests, money problems, ego, and failure into affectionate chaos.',
    coreFantasy: 'Live the fantasy-adventurer dream with the worst possible teammates and realize their dysfunction is the whole reward.',
    pillars: ['party dysfunction', 'isekai parody', 'comic failure', 'character chemistry', 'low-stakes quests'],
    motivations: ['fantasy comedy', 'chaotic ensemble', 'isekai parody', 'comfort rewatching'],
    themes: ['friendship', 'failure', 'ego', 'adventure', 'belonging'],
    emotions: ['hilarious', 'chaotic', 'cozy', 'irreverent', 'affectionate'],
    atmosphere: ['starter fantasy town', 'guild tavern', 'cheap mansion', 'ridiculous quests'],
    vibes: { comedy: 10, chaos: 10, fantasy: 8, spicy: 6, cozy: 7 },
    pacing: 'short comic quest arcs driven by party chemistry',
    followUps: ['space-dandy', 'gintama', 'combatants-will-be-dispatched', 'cautious-hero'],
    avoid: 'Skip if sexual jokes, yelling, or intentionally useless heroes annoy you.'
  }),
  goldCard({
    id: 'fate-zero',
    titles: ['Fate/Zero'],
    aliases: ['Fate Zero'],
    domain: 'tragic ideological battle royale',
    signature: 'Mages and legendary heroes wage a ritual war where competing ideals, ruthless strategy, family sacrifice, and impossible wishes destroy nearly everyone.',
    coreFantasy: 'Command a mythic hero in a secret urban war and test whether your ideal survives contact with everyone else’s desperation.',
    pillars: ['mythic summons', 'strategic conflict', 'ideological clashes', 'adult ensemble', 'tragic inevitability'],
    motivations: ['dark fantasy action', 'strategy', 'moral conflict', 'large ensemble tragedy'],
    themes: ['idealism', 'sacrifice', 'power', 'family', 'fate'],
    emotions: ['grand', 'tense', 'grim', 'tragic', 'philosophical'],
    atmosphere: ['nighttime city war', 'ritual chambers', 'ancient battlefields', 'ruined castles'],
    vibes: { dark: 9, action: 9, fantasy: 9, psychological: 8, emotional: 7 },
    pacing: 'dialogue-heavy setup punctuated by major strategic confrontations',
    complexity: 9,
    followUps: ['code-geass', 'psycho-pass', 'attack-on-titan', 'madoka-magica'],
    avoid: 'Skip if dense lore, grim outcomes, or talk-heavy ideological conflict is not appealing.'
  }),
  goldCard({
    id: 'space-dandy',
    titles: ['Space Dandy'],
    domain: 'cosmic absurdist anthology comedy',
    signature: 'A vain alien hunter bounces through wildly different universes where comedy, animation experiments, melancholy, romance, and cosmic ideas can reset every week.',
    coreFantasy: 'Cruise an unlimited multiverse with lovable idiots and let every episode become a different genre, art style, or philosophical joke.',
    pillars: ['anthology freedom', 'cosmic comedy', 'visual experimentation', 'genre roulette', 'unexpected melancholy'],
    motivations: ['absurd comedy', 'creative animation', 'episodic variety', 'weird science fiction'],
    themes: ['possibility', 'identity', 'loneliness', 'beauty', 'freedom'],
    emotions: ['hilarious', 'surreal', 'carefree', 'wistful', 'wonderstruck'],
    atmosphere: ['colorful galaxies', 'alien diners', 'impossible planets', 'parallel universes'],
    vibes: { comedy: 10, chaos: 10, scifi: 9, emotional: 5, adventure: 8 },
    pacing: 'standalone experimental episodes with near-total creative freedom',
    followUps: ['cowboy-bebop', 'samurai-champloo', 'konosuba', 'gintama'],
    avoid: 'Skip if you need continuity, grounded humor, or a serious protagonist.'
  })
];
