// Gold Standard JoeAI Genome Cards - Pack 3
// Modern Battle Shonen / Action Anchors
// Drop into: src/ai/genome/gold/

export const GOLD_STANDARD_GENOME_CARDS_PACK_3 = [
  {
    id: "attack-on-titan",
    titles: ["Attack on Titan"],
    aliases: ["Shingeki no Kyojin", "AOT"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "war horror / survival mystery",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A desperate survival epic that begins as monster horror and expands into war, propaganda, trauma, moral collapse, and the terrifying cost of freedom.",
    coreFantasy: "Stand against an impossible enemy, uncover the truth behind the walls, and survive long enough to realize the real monster may be the world itself.",
    fantasyPillars: ["survival against giants", "hidden world truth", "military sacrifice", "moral grayness", "revenge becoming ideology", "freedom at any cost"],
    emotionalJourney: ["terror", "rage", "hope", "betrayal", "dread", "moral exhaustion", "devastation"],
    rewardLoop: ["impossible threat", "brutal loss", "tactical counterattack", "mystery clue", "political reveal", "victory with a cost", "worldview shatters"],
    dopamineSources: ["Titan reveals", "ODM gear battles", "basement-level mysteries", "military tactics", "betrayals", "last-stand heroism", "massive plot reversals"],
    viewerType: ["dark shonen fan", "war drama fan", "mystery-box addict", "moral-grayness enjoyer", "high-stakes action fan"],
    viewerMotivations: ["survival tension", "truth reveals", "strategic action", "political conflict", "freedom", "tragic consequences"],
    themes: ["freedom", "war", "propaganda", "revenge", "cycles of hatred", "sacrifice", "identity"],
    emotionalProfile: ["oppressive", "furious", "tragic", "suspenseful", "grand", "bleak"],
    atmosphere: ["militarized", "apocalyptic", "paranoid", "bloody", "mythic", "political"],
    vibes: { action: 9, dark: 10, mystery: 9, emotional: 9, strategy: 8, horror: 8 },
    pacing: "escalating mystery-war epic",
    complexity: 9,
    whyFansLove: ["the stakes feel brutally real", "the mysteries keep expanding the world", "victories always cost something", "the action is desperate instead of casual", "the story keeps questioning its own heroes"],
    whoShouldWatch: "Viewers who want intense survival action, shocking reveals, military drama, and a story that becomes more morally complicated the longer it goes.",
    whoShouldAvoid: "Skip if you dislike heavy violence, bleak war themes, or stories where clean heroes and simple answers disappear.",
    idealFollowUps: ["fullmetal-alchemist-brotherhood", "vinland-saga", "86", "monster", "code-geass"],
    joeNote: "Gold anchor for dark escalation. Weight survival dread, mystery reveals, war trauma, and moral collapse higher than simple action tags."
  },
  {
    id: "demon-slayer",
    titles: ["Demon Slayer: Kimetsu no Yaiba"],
    aliases: ["Kimetsu no Yaiba", "Demon Slayer"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "emotional sword shonen / demon tragedy",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A beautifully animated sword-fighting shonen where every battle is powered by grief, family love, discipline, compassion, and explosive cathartic technique reveals.",
    coreFantasy: "Train your body and heart until you can face monsters without losing your kindness, protecting family even when the world has already taken too much.",
    fantasyPillars: ["family devotion", "sword forms", "beautiful combat", "tragic demons", "training discipline", "kindness under pressure"],
    emotionalJourney: ["grief", "resolve", "fear", "beauty", "compassion", "catharsis", "triumph"],
    rewardLoop: ["demon threat", "emotional backstory", "breathing technique", "near defeat", "visual spectacle", "compassionate closure", "new rank challenge"],
    dopamineSources: ["Breathing Style animations", "Tanjiro's empathy", "Hashira entrances", "tragic villain flashbacks", "beautiful finishing moves", "family loyalty"],
    viewerType: ["emotional action fan", "animation spectacle fan", "sword combat fan", "family-bond viewer", "classic shonen enjoyer"],
    viewerMotivations: ["protecting family", "beautiful fights", "training growth", "emotional release", "good-hearted heroes", "monster tragedy"],
    themes: ["family", "grief", "compassion", "discipline", "humanity", "loss", "perseverance"],
    emotionalProfile: ["earnest", "tragic", "beautiful", "heroic", "cathartic", "warm"],
    atmosphere: ["Taisho supernatural", "colorful", "deadly", "melancholic", "ritualized"],
    vibes: { action: 9, emotional: 9, visualSpectacle: 10, supernatural: 8, shonen: 9 },
    pacing: "mission-based escalation",
    complexity: 6,
    whyFansLove: ["the fights look incredible", "Tanjiro's kindness makes the brutality hit harder", "demons often feel tragic instead of disposable", "the Hashira create instant hype", "family love is the emotional engine"],
    whoShouldWatch: "Viewers who want gorgeous sword fights, sincere emotion, tragic demons, and a hero whose compassion is as important as his technique.",
    whoShouldAvoid: "Skip if you need complex politics, morally gray protagonists, or dislike very earnest shonen emotion.",
    idealFollowUps: ["bleach", "jujutsu-kaisen", "blue-exorcist", "rurouni-kenshin", "dororo"],
    joeNote: "Gold anchor for beautiful emotional action. Do not reduce it to visuals; the family-grief-compassion loop is the soul."
  },
  {
    id: "my-hero-academia",
    titles: ["My Hero Academia"],
    aliases: ["Boku no Hero Academia", "MHA"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.98,
    generated: false,
    needsReview: true,
    domain: "superhero school shonen / legacy underdog",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A superhero academy shonen about inherited power, public ideals, rival growth, and a powerless kid learning what it actually means to save people.",
    coreFantasy: "Start with no power in a world obsessed with powers, inherit a heroic legacy, and prove that the heart to save people matters before the costume ever does.",
    fantasyPillars: ["underdog heroism", "school training", "quirk creativity", "mentor legacy", "class bonds", "public hero ideals"],
    emotionalJourney: ["longing", "hope", "pressure", "growth", "fear", "responsibility", "heroic release"],
    rewardLoop: ["new assignment", "quirk matchup", "student rivalry", "villain pressure", "mentor lesson", "save someone", "hero identity grows"],
    dopamineSources: ["creative powers", "class teamwork", "All Might moments", "Deku breakthroughs", "rival clashes", "hero rankings", "rescue payoffs"],
    viewerType: ["underdog believer", "superhero fan", "school-battle fan", "ensemble cast enjoyer", "training arc fan"],
    viewerMotivations: ["becoming worthy", "saving people", "mentor approval", "team growth", "creative abilities", "hero ideals"],
    themes: ["heroism", "legacy", "society", "expectations", "self-worth", "responsibility", "public image"],
    emotionalProfile: ["inspiring", "earnest", "competitive", "anxious", "hopeful", "dramatic"],
    atmosphere: ["school-based", "bright", "competitive", "heroic", "increasingly unstable"],
    vibes: { shonen: 10, action: 8, school: 8, emotional: 8, teamwork: 8 },
    pacing: "school arcs into society-scale conflict",
    complexity: 7,
    whyFansLove: ["Deku's dream is easy to root for", "quirks make battles creative", "Class 1-A feels like a real group", "All Might gives the story mythic warmth", "the hero society questions get bigger over time"],
    whoShouldWatch: "Viewers who like underdogs, superhero ideals, school tournaments, creative powers, and earnest characters learning what heroism costs.",
    whoShouldAvoid: "Skip if you dislike school settings, large ensemble casts, or very earnest speeches about heroism.",
    idealFollowUps: ["naruto", "black-clover", "tiger-and-bunny", "one-punch-man", "fire-force"],
    joeNote: "Gold anchor for superhero shonen. Weight heroic aspiration, class bonds, inherited legacy, and rescue fantasy over generic school/action tags."
  },
  {
    id: "black-clover",
    titles: ["Black Clover"],
    aliases: [],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "magic knight underdog shonen",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A loud, relentless underdog magic shonen where stubborn effort, squad loyalty, anti-magic, and never-shut-up determination turn rejection into battlefield momentum.",
    coreFantasy: "Be born without magic in a world built on magic, then punch through every ceiling with guts, training, friends, and a power nobody understands.",
    fantasyPillars: ["magic society", "no-magic underdog", "squad found family", "rival dream", "anti-magic weapon identity", "class prejudice"],
    emotionalJourney: ["rejection", "defiance", "belonging", "growth", "team pride", "breakthrough", "hype"],
    rewardLoop: ["mission", "enemy magic", "Asta gets outmatched", "squad combo", "anti-magic breakthrough", "rival progress", "rank respect"],
    dopamineSources: ["anti-magic sword reveals", "Black Bulls chaos", "team combo attacks", "rival growth", "captain hype", "impossible comeback energy"],
    viewerType: ["classic shonen fan", "underdog addict", "team-battle fan", "magic power-system fan", "hype comeback viewer"],
    viewerMotivations: ["prove everyone wrong", "team belonging", "magic battles", "rivalry", "hard work", "found family"],
    themes: ["classism", "effort", "friendship", "ambition", "belonging", "prejudice", "self-belief"],
    emotionalProfile: ["loud", "optimistic", "hype", "scrappy", "warm", "defiant"],
    atmosphere: ["fantasy kingdom", "guild-like squads", "chaotic", "competitive", "battle-heavy"],
    vibes: { shonen: 10, action: 9, comedy: 7, teamwork: 9, fantasy: 9 },
    pacing: "long-form mission and war escalation",
    complexity: 7,
    whyFansLove: ["Asta's stubbornness becomes infectious", "the Black Bulls feel like lovable disasters", "team fights are satisfying", "the magic types keep battles varied", "it delivers classic shonen hype without shame"],
    whoShouldWatch: "Viewers who want a big-hearted underdog shonen with magic squads, team attacks, rivalry, and nonstop comeback energy.",
    whoShouldAvoid: "Skip if loud protagonists or long-running shonen pacing drive you crazy.",
    idealFollowUps: ["naruto", "fairy-tail", "my-hero-academia", "magi", "seven-deadly-sins"],
    joeNote: "Gold anchor for pure underdog magic hype. Weight found-squad loyalty and anti-magic identity strongly."
  },
  {
    id: "fire-force",
    titles: ["Fire Force"],
    aliases: ["Enen no Shouboutai"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "pyrokinetic exorcist action / conspiracy shonen",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A stylish supernatural firefighting shonen where flame powers, religious mystery, rescue work, body horror, and conspiracy lore burn underneath every explosive fight.",
    coreFantasy: "Join a special fire brigade, master a terrifying flame power, save people from human combustion, and uncover the truth behind a world literally burning from the inside.",
    fantasyPillars: ["fire brigade heroism", "pyrokinetic powers", "human combustion horror", "religious conspiracy", "squad identity", "rescue through battle"],
    emotionalJourney: ["shock", "hype", "suspicion", "grief", "revelation", "resolve", "combustive triumph"],
    rewardLoop: ["infernal incident", "rescue mission", "fire-power clash", "company mystery", "Adolla clue", "squad upgrade", "conspiracy deepens"],
    dopamineSources: ["flame ability creativity", "sound-design impact", "Shinra kick bursts", "company rivalries", "religious mystery", "squad entrances"],
    viewerType: ["stylish action fan", "supernatural shonen fan", "power-system enjoyer", "conspiracy lore fan", "rescue-hero viewer"],
    viewerMotivations: ["cool powers", "team missions", "hidden truth", "hero rescue fantasy", "religious mystery", "explosive fights"],
    themes: ["faith", "truth", "heroism", "trauma", "sacrifice", "corruption", "fear of becoming a monster"],
    emotionalProfile: ["flashy", "weird", "heroic", "ominous", "kinetic", "mysterious"],
    atmosphere: ["industrial", "religious", "smoky", "urban fantasy", "combustive"],
    vibes: { action: 9, style: 9, supernatural: 9, mystery: 8, comedy: 6 },
    pacing: "mission-based action with conspiracy escalation",
    complexity: 7,
    whyFansLove: ["the fights have insane visual and sound impact", "fire powers stay creative", "the brigade structure gives it a strong identity", "the mystery gets stranger over time", "Shinra has classic protector energy"],
    whoShouldWatch: "Viewers who want stylish supernatural action, squad-based missions, fire powers, rescue stakes, and a conspiracy hiding under the smoke.",
    whoShouldAvoid: "Skip if fanservice interruptions or tonal whiplash bother you a lot.",
    idealFollowUps: ["soul-eater", "blue-exorcist", "bleach", "jujutsu-kaisen", "my-hero-academia"],
    joeNote: "Gold anchor for style-plus-conspiracy shonen. Weight fire brigade identity and rescue/exorcism energy over generic powers."
  },
  {
    id: "blue-exorcist",
    titles: ["Blue Exorcist"],
    aliases: ["Ao no Exorcist"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.97,
    generated: false,
    needsReview: true,
    domain: "demon-blood academy exorcist shonen",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A supernatural school shonen about the son of Satan choosing exorcist training, found family, brother tension, and the fear that your own nature might make you the enemy.",
    coreFantasy: "Carry demonic power inside you, reject the destiny everyone expects, and train to protect people from the very darkness you were born from.",
    fantasyPillars: ["demon lineage", "exorcist academy", "brother conflict", "hidden identity", "found family", "power feared by allies"],
    emotionalJourney: ["shame", "anger", "belonging", "fear", "discipline", "acceptance", "resolve"],
    rewardLoop: ["school lesson", "demon attack", "identity pressure", "team conflict", "blue flame reveal", "exorcist growth", "family truth"],
    dopamineSources: ["blue flame moments", "academy training", "demon lore", "brother drama", "classmate bonds", "Rin's chaotic heart"],
    viewerType: ["supernatural school fan", "demon-power fan", "found-family viewer", "brother-drama enjoyer", "classic shonen fan"],
    viewerMotivations: ["controlling inner darkness", "training to protect", "being accepted", "hidden powers", "exorcist missions", "family conflict"],
    themes: ["identity", "nature versus choice", "family", "acceptance", "faith", "fear", "responsibility"],
    emotionalProfile: ["angsty", "warm", "supernatural", "scrappy", "hopeful", "dramatic"],
    atmosphere: ["academy", "church occult", "urban supernatural", "demon-haunted", "youthful"],
    vibes: { supernatural: 9, school: 8, action: 7, emotional: 8, comedy: 6 },
    pacing: "school training into exorcist conflict",
    complexity: 6,
    whyFansLove: ["Rin is a lovable chaos gremlin with a good heart", "the exorcist academy has strong comfort-watch energy", "the blue flames are iconic", "the sibling tension gives the story bite", "the show balances darkness with warmth"],
    whoShouldWatch: "Viewers who enjoy demon powers, exorcist schools, found family, brother conflict, and heroes fighting against the identity assigned to them.",
    whoShouldAvoid: "Skip if you need very tight plot continuity or dislike academy structures.",
    idealFollowUps: ["bleach", "demon-slayer", "fire-force", "soul-eater", "jujutsu-kaisen"],
    joeNote: "Gold anchor for demon-identity shonen. Weight chosen identity and acceptance over generic exorcist action."
  },
  {
    id: "kaiju-no-8",
    titles: ["Kaiju No. 8"],
    aliases: ["Kaijuu 8-gou", "Kaiju No 8"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.96,
    generated: false,
    needsReview: true,
    domain: "late-bloomer monster soldier shonen",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A monster-fighting action shonen about an adult underdog getting one last shot at his childhood dream after becoming the very kind of kaiju he swore to fight.",
    coreFantasy: "Be the guy who thought his dream had passed him by, then get a terrifying second chance and prove you can still stand beside the heroes you admire.",
    fantasyPillars: ["adult underdog", "kaiju transformation", "defense force dream", "second chance", "monster identity", "squad proving ground"],
    emotionalJourney: ["regret", "hope", "panic", "training", "belonging", "reveal fear", "earned confidence"],
    rewardLoop: ["kaiju incident", "Kafka hides power", "training test", "squad teamwork", "monster form saves lives", "secret risk", "rank progress"],
    dopamineSources: ["Kaiju form punches", "adult comeback energy", "Defense Force tests", "squad respect", "Mina promise", "monster cleanup perspective"],
    viewerType: ["late-bloomer viewer", "monster action fan", "underdog shonen fan", "adult protagonist enjoyer", "team military fan"],
    viewerMotivations: ["second chances", "proving yourself", "monster power", "team acceptance", "childhood dreams", "hero rescue fantasy"],
    themes: ["regret", "ambition", "identity", "aging dreams", "teamwork", "heroism", "self-worth"],
    emotionalProfile: ["funny", "hopeful", "hype", "anxious", "scrappy", "uplifting"],
    atmosphere: ["military training", "urban kaiju", "workplace shonen", "clean-up crew grit", "battlefield"],
    vibes: { action: 8, shonen: 8, comedy: 7, underdog: 10, teamwork: 8 },
    pacing: "exam-to-squad escalation",
    complexity: 6,
    whyFansLove: ["Kafka gives the underdog fantasy an adult spin", "the kaiju power is instantly satisfying", "the squad dynamic is easy to root for", "the childhood promise gives emotional direction", "it mixes goofy energy with real stakes"],
    whoShouldWatch: "Viewers who want a modern shonen with an adult underdog, monster powers, squad tests, and the feeling that it's not too late to chase the dream.",
    whoShouldAvoid: "Skip if you dislike secret-identity setups or want a darker, more brutal kaiju story.",
    idealFollowUps: ["my-hero-academia", "attack-on-titan", "world-trigger", "solo-leveling", "fire-force"],
    joeNote: "Gold anchor for adult second-chance shonen. Weight late-bloomer dream recovery heavily."
  },
  {
    id: "solo-leveling",
    titles: ["Solo Leveling"],
    aliases: ["Ore dake Level Up na Ken"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.96,
    generated: false,
    needsReview: true,
    domain: "power progression dungeon fantasy",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A pure progression fantasy about the weakest hunter receiving a private leveling system and turning every dungeon, corpse, and boss fight into fuel for unstoppable transformation.",
    coreFantasy: "Start as the weakest person in the room, gain a secret system only you can use, and grind until the world has to recalculate what power means.",
    fantasyPillars: ["weakest-to-strongest climb", "game-like system", "solo dungeon grind", "shadow army", "secret power", "intimidating transformation"],
    emotionalJourney: ["humiliation", "terror", "survival", "discipline", "confidence", "dominance", "awe"],
    rewardLoop: ["deadly dungeon", "near death", "quest reward", "stat increase", "new skill", "boss fight", "power flex"],
    dopamineSources: ["level-up notifications", "stat growth", "boss executions", "shadow extraction", "aura intimidation", "weak-to-OP transformation"],
    viewerType: ["power fantasy fan", "RPG system enjoyer", "dungeon crawler fan", "OP protagonist viewer", "grind-to-glory addict"],
    viewerMotivations: ["getting stronger", "revenge on weakness", "solo dominance", "loot and skills", "ranking up", "protecting family through power"],
    themes: ["survival", "power", "self-reinvention", "isolation", "ambition", "family responsibility", "fear becoming respect"],
    emotionalProfile: ["intense", "cool", "addictive", "lonely", "dominant", "hype"],
    atmosphere: ["dungeon-lit", "game-system", "deadly", "sleek", "shadowy"],
    vibes: { action: 9, powerFantasy: 10, dark: 7, progression: 10, emotional: 5 },
    pacing: "rapid progression escalation",
    complexity: 5,
    whyFansLove: ["the power climb is extremely addictive", "Jinwoo's transformation is satisfying", "the system rewards make each win feel tangible", "the shadow army is a killer hook", "it delivers clean power-fantasy dopamine"],
    whoShouldWatch: "Viewers who want fast, stylish, RPG-like power progression where every fight clearly makes the hero stronger.",
    whoShouldAvoid: "Skip if you need deep ensemble drama, balanced fights, or complex moral conflict over power fantasy momentum.",
    idealFollowUps: ["kaiju-no-8", "tower-of-god", "the-god-of-high-school", "overlord", "that-time-i-got-reincarnated-as-a-slime"],
    joeNote: "Gold anchor for progression dopamine. Weight leveling, solo grind, intimidation, and transformation payoff over generic fantasy/action."
  },
  {
    id: "hells-paradise",
    titles: ["Hell's Paradise"],
    aliases: ["Jigokuraku"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.96,
    generated: false,
    needsReview: true,
    domain: "violent survival fantasy / death-row expedition",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A beautiful and brutal survival anime where condemned killers and executioners explore a paradise island that hides body horror, spiritual power, and questions about what makes someone human.",
    coreFantasy: "Enter a gorgeous hellscape where every flower might kill you, every criminal has a reason to live, and survival means confronting the violence inside yourself.",
    fantasyPillars: ["death-row mission", "beautiful horror island", "executioner bonds", "Tao power", "killer humanity", "survival mystery"],
    emotionalJourney: ["dread", "curiosity", "violence", "vulnerability", "wonder", "terror", "hard-earned trust"],
    rewardLoop: ["island discovery", "grotesque threat", "killer backstory", "executioner tension", "power clue", "brutal fight", "humanizing moment"],
    dopamineSources: ["strange island reveals", "deadly matchups", "Gabimaru's contradictions", "beautiful body horror", "criminal backstories", "survival alliances"],
    viewerType: ["dark fantasy fan", "survival horror viewer", "seinen-action enjoyer", "morally gray cast fan", "mystery island addict"],
    viewerMotivations: ["survive the unknown", "explore forbidden paradise", "understand killers", "brutal action", "spiritual mystery", "redemption possibility"],
    themes: ["humanity", "violence", "love", "redemption", "survival", "identity", "the beauty of death"],
    emotionalProfile: ["brutal", "mysterious", "beautiful", "uneasy", "tragic", "intense"],
    atmosphere: ["lush", "poisonous", "grotesque", "spiritual", "humid", "dangerous"],
    vibes: { dark: 9, action: 8, horror: 8, mystery: 8, emotional: 7 },
    pacing: "survival expedition escalation",
    complexity: 7,
    whyFansLove: ["the island is gorgeous and horrifying", "Gabimaru is deadly but emotionally interesting", "the cast is full of dangerous people with reasons to live", "the power system feels spiritual and strange", "beauty and violence are constantly tangled"],
    whoShouldWatch: "Viewers who want brutal dark fantasy, survival mystery, morally gray characters, and a beautiful setting that feels completely unsafe.",
    whoShouldAvoid: "Skip if you dislike gore, body horror, or stories centered on criminals and executioners.",
    idealFollowUps: ["dorohedoro", "dororo", "attack-on-titan", "blade-of-the-immortal", "jujutsu-kaisen"],
    joeNote: "Gold anchor for beautiful brutality. Weight survival mystery, body horror, and killer-humanity tension."
  },
  {
    id: "wind-breaker",
    titles: ["Wind Breaker"],
    aliases: ["WIND BREAKER"],
    quality: "gold",
    generationQuality: "curated",
    confidence: 0.95,
    generated: false,
    needsReview: true,
    domain: "delinquent brotherhood / street protection drama",
    subdomain: "gold standard audience-fantasy profile",
    signature: "A delinquent fighting anime about a lonely brawler discovering that strength can mean protecting a town, accepting friendship, and belonging to something bigger than your fists.",
    coreFantasy: "Walk into a school of feared fighters expecting violence and find a brotherhood that uses strength to protect the people everyone else ignores.",
    fantasyPillars: ["street fights", "protective delinquents", "found brotherhood", "lonely fighter healing", "town loyalty", "respect through fists"],
    emotionalJourney: ["isolation", "suspicion", "shock", "acceptance", "pride", "loyalty", "belonging"],
    rewardLoop: ["new rival", "street confrontation", "values clash", "fight with meaning", "respect earned", "group bond", "town protected"],
    dopamineSources: ["clean hand-to-hand fights", "delinquent honor codes", "Sakura's awkward growth", "crew loyalty", "protect-the-neighborhood energy", "respect moments"],
    viewerType: ["delinquent anime fan", "found-family viewer", "street-fight fan", "character-growth enjoyer", "brotherhood-energy fan"],
    viewerMotivations: ["belonging", "earning respect", "protecting people", "street camaraderie", "personal growth", "fights with emotional rules"],
    themes: ["belonging", "strength", "community", "respect", "loneliness", "masculinity", "protection"],
    emotionalProfile: ["warm", "scrappy", "sincere", "cool", "protective", "uplifting"],
    atmosphere: ["street-level", "school turf", "neighborhood", "bright delinquent", "loyal"],
    vibes: { action: 8, friendship: 9, delinquent: 10, emotional: 7, comedy: 6 },
    pacing: "rival fights into brotherhood growth",
    complexity: 5,
    whyFansLove: ["the fights are clean and personal", "the delinquent setup is surprisingly wholesome", "Sakura learning friendship is satisfying", "the town-protection angle gives the violence heart", "the crew has strong ride-or-die energy"],
    whoShouldWatch: "Viewers who want stylish street fights, delinquent honor, found brotherhood, and a lonely fighter slowly learning how to belong.",
    whoShouldAvoid: "Skip if you want supernatural powers, heavy plot complexity, or morally grim gang politics.",
    idealFollowUps: ["tokyo-revengers", "slam-dunk", "great-teacher-onizuka", "megalo-box", "my-hero-academia"],
    joeNote: "Gold anchor for wholesome delinquent protection. Do not confuse it with pure gang crime; the core fantasy is belonging through protective strength."
  }
];
