// Gold Standard JoeAI Genome Cards - Pack 7
// Major audience anchors that upgrade older profiles and fill discovery gaps.

function goldCard({
  id,
  titles,
  aliases = [],
  domain,
  signature,
  coreFantasy,
  pillars,
  motivations,
  themes,
  emotions,
  atmosphere,
  vibes,
  pacing,
  complexity = 7,
  followUps,
  avoid
}) {
  return {
    id,
    titles,
    aliases,
    quality: 'gold',
    generationQuality: 'curated',
    confidence: 0.98,
    generated: false,
    needsReview: false,
    domain,
    subdomain: 'gold standard audience-fantasy profile',
    signature,
    description: signature,
    coreFantasy,
    fantasyPillars: pillars,
    emotionalJourney: emotions.slice(0, 6),
    rewardLoop: pillars.slice(0, 6),
    dopamineSources: [...pillars.slice(0, 3), ...motivations.slice(0, 3)],
    viewerType: motivations.map((motivation) => `${motivation} viewer`).slice(0, 4),
    viewerMotivations: motivations,
    whyPick: motivations,
    bestFor: `Viewers looking for ${motivations.slice(0, 3).join(', ')}.`,
    themes,
    emotionalProfile: emotions,
    atmosphere,
    vibes,
    pacing,
    complexity,
    whyFansLove: [signature, ...pillars.slice(0, 4)],
    whoShouldWatch: `Watch when you want ${motivations.slice(0, 4).join(', ')}.`,
    whoShouldAvoid: avoid,
    idealFollowUps: followUps,
    nearbyPicks: followUps,
    joeNote: `Gold anchor for ${domain}. Weight the experience profile over surface genre overlap.`
  };
}

export const GOLD_STANDARD_GENOME_CARDS_PACK_7 = [
  goldCard({
    id: 'dragon-ball-z',
    titles: ['Dragon Ball Z'],
    aliases: ['DBZ'],
    domain: 'martial-arts power escalation',
    signature: 'The transformation-and-rivalry blueprint: heroic fighters train past impossible limits, collide with cosmic threats, and turn raw power into generational myth.',
    coreFantasy: 'Break every limit beside iconic rivals and protect the world through willpower, training, and spectacular strength.',
    pillars: ['training breakthroughs', 'transformations', 'rivalry', 'planet-scale battles', 'heroic endurance'],
    motivations: ['power progression', 'battle hype', 'iconic heroes', 'simple heroic stakes'],
    themes: ['self-improvement', 'rivalry', 'family', 'sacrifice', 'redemption'],
    emotions: ['hype', 'heroic', 'tense', 'triumphant', 'nostalgic'],
    atmosphere: ['martial-arts arenas', 'alien worlds', 'wilderness training grounds', 'destroyed cities'],
    vibes: { action: 10, mastery: 10, adventure: 8, emotional: 5, comedy: 5 },
    pacing: 'long escalation arcs punctuated by training and explosive breakthroughs',
    followUps: ['naruto', 'bleach', 'one-piece', 'my-hero-academia'],
    avoid: 'Skip if long fights, repeated power escalation, or straightforward morality wear you down.'
  }),
  goldCard({
    id: 'sailor-moon',
    titles: ['Sailor Moon'],
    aliases: ['Pretty Guardian Sailor Moon'],
    domain: 'magical-girl friendship epic',
    signature: 'A romantic cosmic adventure where ordinary schoolgirls become planetary guardians through friendship, compassion, and luminous transformation.',
    coreFantasy: 'Discover a hidden celestial identity and save the world with friends whose love is stronger than destiny.',
    pillars: ['magical transformations', 'team friendship', 'romantic destiny', 'monster battles', 'cosmic mythology'],
    motivations: ['found-family warmth', 'magical spectacle', 'heroic romance', 'optimistic adventure'],
    themes: ['friendship', 'love', 'identity', 'destiny', 'compassion'],
    emotions: ['hopeful', 'romantic', 'funny', 'earnest', 'triumphant'],
    atmosphere: ['moonlit Tokyo', 'school life', 'celestial kingdoms', 'sparkling battlefields'],
    vibes: { wholesome: 9, romance: 8, action: 7, fantasy: 10, emotional: 7 },
    pacing: 'episodic threats that build into larger team and destiny arcs',
    followUps: ['madoka-magica', 'cardcaptor-sakura', 'revolutionary-girl-utena', 'princess-tutu'],
    avoid: 'Skip if repeated transformation sequences or older episodic pacing are barriers.'
  }),
  goldCard({
    id: 'berserk',
    titles: ['Berserk'],
    domain: 'dark medieval survival tragedy',
    signature: 'A brutal saga of ambition, brotherhood, betrayal, and trauma where one swordsman fights fate itself without surrendering the fragile bonds that keep him human.',
    coreFantasy: 'Survive an unforgiving world with impossible strength while reclaiming agency from destiny, monsters, and the wounds of betrayal.',
    pillars: ['tragic brotherhood', 'relentless survival', 'medieval warfare', 'cosmic horror', 'defiance of fate'],
    motivations: ['dark fantasy', 'psychological character drama', 'tragic epic', 'visceral combat'],
    themes: ['fate', 'ambition', 'trauma', 'friendship', 'human will'],
    emotions: ['grim', 'furious', 'intimate', 'horrifying', 'tragic'],
    atmosphere: ['muddy battlefields', 'medieval courts', 'haunted wilderness', 'nightmare dimensions'],
    vibes: { dark: 10, action: 9, horror: 10, psychological: 9, emotional: 10 },
    pacing: 'large historical arcs that descend into intimate and supernatural catastrophe',
    complexity: 9,
    followUps: ['vinland-saga', 'claymore', 'attack-on-titan', 'devilman-crybaby'],
    avoid: 'Skip if sexual violence, extreme gore, abuse, or unresolved trauma are unsafe for you.'
  }),
  goldCard({
    id: 'madoka-magica',
    titles: ['Puella Magi Madoka Magica'],
    aliases: ['Madoka Magica', 'Mahou Shoujo Madoka Magica'],
    domain: 'tragic magical-girl deconstruction',
    signature: 'A compact magical-girl tragedy that turns wishes, hope, entropy, and sacrifice into a merciless moral system without losing faith in compassion.',
    coreFantasy: 'Be offered the power to save others and discover the true cost hidden inside every beautiful wish.',
    pillars: ['wish economy', 'time-loop tragedy', 'female friendship', 'surreal horror', 'cosmic sacrifice'],
    motivations: ['psychological fantasy', 'tight mystery', 'tragic friendship', 'conceptual payoff'],
    themes: ['hope', 'despair', 'sacrifice', 'friendship', 'agency'],
    emotions: ['beautiful', 'anxious', 'devastating', 'surreal', 'cathartic'],
    atmosphere: ['ordinary school days', 'paper-cut labyrinths', 'moonlit cities', 'cosmic voids'],
    vibes: { psychological: 10, dark: 10, fantasy: 9, mystery: 9, emotional: 10 },
    pacing: 'short, controlled escalation with major contextual reversals',
    complexity: 9,
    followUps: ['sailor-moon', 'revolutionary-girl-utena', 'steins-gate', 'made-in-abyss'],
    avoid: 'Skip if child endangerment, despair, or deceptive tonal shifts are dealbreakers.'
  }),
  goldCard({
    id: 'monogatari-series',
    titles: ['Monogatari Series'],
    aliases: ['Bakemonogatari', 'Monogatari'],
    domain: 'dialogue-driven supernatural psychology',
    signature: 'A visually radical web of ghost stories where wordplay, unreliable perspective, desire, and self-deception make every supernatural problem intensely personal.',
    coreFantasy: 'Talk through impossible apparitions and discover that saving someone requires confronting the story they tell about themselves.',
    pillars: ['dense dialogue', 'unreliable narration', 'apparition metaphors', 'visual experimentation', 'interlocking character arcs'],
    motivations: ['psychological dialogue', 'formal experimentation', 'complex characters', 'supernatural mystery'],
    themes: ['identity', 'desire', 'self-deception', 'trauma', 'responsibility'],
    emotions: ['witty', 'intimate', 'unsettling', 'cerebral', 'provocative'],
    atmosphere: ['empty cities', 'stylized classrooms', 'shrines', 'abstract interior spaces'],
    vibes: { psychological: 10, mystery: 8, romance: 7, comedy: 8, experimental: 10 },
    pacing: 'extended conversations interrupted by sudden visual and emotional ruptures',
    complexity: 10,
    followUps: ['serial-experiments-lain', 'rascal-does-not-dream-of-bunny-girl-senpai', 'oregairu', 'revolutionary-girl-utena'],
    avoid: 'Skip if fan service, taboo humor, dense wordplay, or nonlinear chronology are hard limits.'
  }),
  goldCard({
    id: 'oregairu',
    titles: ['My Teen Romantic Comedy SNAFU'],
    aliases: ['Oregairu', 'Yahari Ore no Seishun Love Comedy wa Machigatteiru'],
    domain: 'socially defensive youth drama',
    signature: 'A school romantic drama about brilliant, wounded teenagers using cynicism, competence, and indirect language to avoid asking for genuine connection.',
    coreFantasy: 'Decode a room full of guarded people and risk dropping your defenses for something emotionally genuine.',
    pillars: ['subtext-heavy dialogue', 'social problem solving', 'emotional avoidance', 'slow romantic tension', 'earned vulnerability'],
    motivations: ['character subtext', 'slow-burn relationships', 'social psychology', 'emotionally guarded leads'],
    themes: ['authenticity', 'loneliness', 'pride', 'friendship', 'vulnerability'],
    emotions: ['wry', 'awkward', 'melancholic', 'tense', 'tender'],
    atmosphere: ['service club room', 'quiet school corridors', 'rainy streets', 'formal events'],
    vibes: { romance: 8, psychological: 9, comedy: 6, emotional: 9, wholesome: 5 },
    pacing: 'slow interpersonal accumulation with major subtextual confrontations',
    complexity: 9,
    followUps: ['toradora', 'monogatari-series', 'bunny-girl-senpai', 'hyouka'],
    avoid: 'Skip if indirect communication or deliberately frustrating emotional avoidance annoys you.'
  }),
  goldCard({
    id: 'toradora',
    titles: ['Toradora!'],
    aliases: ['Toradora'],
    domain: 'messy first-love ensemble comedy',
    signature: 'Two intimidating classmates scheme to reach their crushes and instead build a domestic, combative friendship that forces an honest reckoning with love.',
    coreFantasy: 'Fall for the person who sees your messiest self while friendship, family wounds, and teenage desire collide.',
    pillars: ['opposites chemistry', 'romantic misdirection', 'domestic intimacy', 'ensemble conflict', 'emotional confession'],
    motivations: ['romantic payoff', 'character chemistry', 'comedy with drama', 'flawed teenagers'],
    themes: ['love', 'family', 'self-image', 'friendship', 'honesty'],
    emotions: ['funny', 'warm', 'frustrating', 'romantic', 'cathartic'],
    atmosphere: ['school corridors', 'small apartments', 'holiday streets', 'class trips'],
    vibes: { romance: 10, comedy: 8, emotional: 9, wholesome: 7, drama: 8 },
    pacing: 'comic partnership that develops into increasingly serious relationship arcs',
    followUps: ['oregairu', 'kaguya-sama-love-is-war', 'horimiya', 'fruits-basket'],
    avoid: 'Skip if tsundere aggression or prolonged romantic misunderstanding is a hard no.'
  }),
  goldCard({
    id: 'fruits-basket',
    titles: ['Fruits Basket'],
    aliases: ['Fruits Basket 2019'],
    domain: 'healing family-curse drama',
    signature: 'A compassionate outsider enters a beautiful, abusive family system and helps its members name grief, reject inherited roles, and imagine freedom.',
    coreFantasy: 'Create a home through radical kindness and help wounded people break a curse sustained by fear and obligation.',
    pillars: ['found family', 'intergenerational trauma', 'slow healing', 'romantic growth', 'curse mythology'],
    motivations: ['emotional healing', 'large attached ensemble', 'gentle romance', 'family drama'],
    themes: ['abuse', 'belonging', 'grief', 'identity', 'breaking cycles'],
    emotions: ['warm', 'sad', 'tender', 'painful', 'hopeful'],
    atmosphere: ['quiet family homes', 'school seasons', 'mountain estates', 'rainy gardens'],
    vibes: { emotional: 10, romance: 8, wholesome: 8, dark: 6, drama: 10 },
    pacing: 'patient ensemble healing that resolves into a sustained final reckoning',
    followUps: ['nana', 'clannad-after-story', 'violet-evergarden', 'march-comes-in-like-a-lion'],
    avoid: 'Skip if abuse dynamics, grief, or a long ensemble investment are not right for you.'
  }),
  goldCard({
    id: 'nana',
    titles: ['NANA'],
    aliases: ['Nana'],
    domain: 'adult friendship and music melodrama',
    signature: 'Two young women with the same name build an intense friendship in Tokyo while music, romance, ambition, dependency, and adulthood pull their lives apart.',
    coreFantasy: 'Share a city apartment with the person who becomes your emotional home while adulthood refuses to stay simple.',
    pillars: ['female friendship', 'music ambition', 'adult romance', 'messy dependency', 'urban coming of age'],
    motivations: ['adult relationship drama', 'music culture', 'complex friendship', 'emotional realism'],
    themes: ['friendship', 'ambition', 'dependency', 'love', 'adulthood'],
    emotions: ['stylish', 'romantic', 'intimate', 'frustrating', 'heartbreaking'],
    atmosphere: ['Tokyo apartments', 'punk clubs', 'train platforms', 'backstage rooms'],
    vibes: { emotional: 10, romance: 9, music: 9, drama: 10, wholesome: 3 },
    pacing: 'relationship-focused serial drama with accumulating consequences',
    complexity: 9,
    followUps: ['fruits-basket', 'beck', 'kids-on-the-slope', 'paradise-kiss'],
    avoid: 'Skip if toxic relationships, infidelity, pregnancy, or unresolved source material are hard limits.'
  }),
  goldCard({
    id: 'clannad-after-story',
    titles: ['Clannad: After Story'],
    aliases: ['Clannad After Story'],
    domain: 'family life and grief drama',
    signature: 'A romance grows beyond graduation into work, marriage, parenthood, loss, and the painful discovery that family is both vulnerability and salvation.',
    coreFantasy: 'Build an ordinary life with the person you love and endure the ways adulthood can break and remake a family.',
    pillars: ['life after school', 'marriage', 'parenthood', 'grief', 'generational reconciliation'],
    motivations: ['life-spanning romance', 'emotional catharsis', 'family drama', 'earned adulthood'],
    themes: ['family', 'grief', 'parenthood', 'memory', 'second chances'],
    emotions: ['gentle', 'romantic', 'devastating', 'lonely', 'cathartic'],
    atmosphere: ['small town streets', 'family homes', 'winter fields', 'quiet workplaces'],
    vibes: { emotional: 10, romance: 9, wholesome: 7, dark: 7, drama: 10 },
    pacing: 'school-life continuation that becomes an adult family epic',
    followUps: ['fruits-basket', 'violet-evergarden', 'anohana', 'your-lie-in-april'],
    avoid: 'Skip if intense grief, sentimentality, or a required first season are barriers.'
  }),
  goldCard({
    id: 'nichijou',
    titles: ['Nichijou'],
    aliases: ['Nichijou: My Ordinary Life'],
    domain: 'surreal everyday comedy',
    signature: 'Ordinary school life detonates into operatic animation, absurd non sequiturs, tiny social disasters, and sincere friendship without needing conventional stakes.',
    coreFantasy: 'Experience daily life as an unlimited animation playground where a dropped lunch can feel apocalyptic.',
    pillars: ['visual escalation', 'absurd sketches', 'friendship chemistry', 'deadpan contrast', 'animation spectacle'],
    motivations: ['surreal comedy', 'animation craft', 'low-stakes comfort', 'ensemble chaos'],
    themes: ['friendship', 'ordinary life', 'embarrassment', 'play', 'belonging'],
    emotions: ['hilarious', 'chaotic', 'cozy', 'surprising', 'joyful'],
    atmosphere: ['school halls', 'quiet neighborhoods', 'science club rooms', 'impossible fantasy cutaways'],
    vibes: { comedy: 10, chaos: 10, wholesome: 9, experimental: 7, emotional: 4 },
    pacing: 'rapid sketches and recurring bits with no plot pressure',
    followUps: ['saiki-k', 'daily-lives-of-high-school-boys', 'azumanga-daioh', 'bocchi-the-rock'],
    avoid: 'Skip if random sketch comedy or minimal plot leaves you cold.'
  }),
  goldCard({
    id: 'grand-blue',
    titles: ['Grand Blue Dreaming'],
    aliases: ['Grand Blue'],
    domain: 'college friendship farce',
    signature: 'A diving-club comedy where college freedom becomes drinking, humiliation, body comedy, and surprisingly sincere friendship beneath the chaos.',
    coreFantasy: 'Join the loudest possible college friend group and discover an adventurous home inside its terrible decisions.',
    pillars: ['college ensemble', 'escalating farce', 'diving wonder', 'friendship loyalty', 'shameless body comedy'],
    motivations: ['adult-ish comedy', 'friend-group chaos', 'vacation atmosphere', 'low-stakes fun'],
    themes: ['friendship', 'freedom', 'belonging', 'adventure', 'self-confidence'],
    emotions: ['raucous', 'embarrassing', 'warm', 'carefree', 'energetic'],
    atmosphere: ['seaside town', 'dive shop', 'college parties', 'clear ocean'],
    vibes: { comedy: 10, chaos: 10, wholesome: 6, adventure: 5, romance: 3 },
    pacing: 'episodic social catastrophes with occasional diving calm',
    followUps: ['konosuba', 'daily-lives-of-high-school-boys', 'gintama', 'prison-school'],
    avoid: 'Skip if alcohol humor, nudity, shouting, or crude comedy are dealbreakers.'
  }),
  goldCard({
    id: 'saiki-k',
    titles: ['The Disastrous Life of Saiki K.'],
    aliases: ['Saiki K', 'Saiki Kusuo no Psi-nan'],
    domain: 'psychic deadpan school comedy',
    signature: 'An all-powerful psychic tries to preserve an ordinary, quiet life while a relentlessly lovable cast makes privacy impossible.',
    coreFantasy: 'Have every supernatural advantage imaginable and still be defeated by friendship, social obligation, and dessert.',
    pillars: ['deadpan narration', 'rapid jokes', 'eccentric ensemble', 'secret powers', 'reluctant friendship'],
    motivations: ['fast comedy', 'overpowered protagonist parody', 'ensemble familiarity', 'low-stakes comfort'],
    themes: ['privacy', 'friendship', 'normalcy', 'identity', 'acceptance'],
    emotions: ['dry', 'chaotic', 'comfortable', 'clever', 'warm'],
    atmosphere: ['busy classrooms', 'quiet bedrooms', 'dessert shops', 'absurd psychic emergencies'],
    vibes: { comedy: 10, chaos: 8, wholesome: 8, psychological: 3, action: 3 },
    pacing: 'very fast short-form scenarios with recurring character payoffs',
    followUps: ['nichijou', 'mob-psycho-100', 'one-punch-man', 'gintama'],
    avoid: 'Skip if hyper-fast subtitles, repeated character bits, or gag-first storytelling exhaust you.'
  }),
  goldCard({
    id: 'one-punch-man',
    titles: ['One-Punch Man'],
    aliases: ['One Punch Man', 'OPM'],
    domain: 'overpowered superhero satire',
    signature: 'The strongest hero alive can end every fight instantly, turning spectacular action into a comedy about boredom, recognition, purpose, and what heroism looks like without struggle.',
    coreFantasy: 'Possess unbeatable power and search for meaning in a world that cannot understand your actual strength.',
    pillars: ['overpowered hero', 'superhero bureaucracy', 'spectacle parody', 'deadpan comedy', 'underdog supporting cast'],
    motivations: ['action spectacle', 'power fantasy satire', 'deadpan comedy', 'hero-world ensemble'],
    themes: ['purpose', 'recognition', 'heroism', 'effort', 'boredom'],
    emotions: ['hilarious', 'hype', 'detached', 'earnest', 'triumphant'],
    atmosphere: ['monster-ravaged cities', 'hero headquarters', 'ordinary apartments', 'impossible battlefields'],
    vibes: { action: 10, comedy: 10, mastery: 9, chaos: 8, emotional: 4 },
    pacing: 'short crisis arcs that juxtapose huge buildup with instant resolution',
    followUps: ['mob-psycho-100', 'saiki-k', 'eminence-in-shadow', 'my-hero-academia'],
    avoid: 'Skip if parody undercuts the battle tension you want from action anime.'
  }),
  goldCard({
    id: 'eminence-in-shadow',
    titles: ['The Eminence in Shadow'],
    aliases: ['Eminence in Shadow', 'Kage no Jitsuryokusha ni Naritakute'],
    domain: 'chuunibyou power-fantasy parody',
    signature: 'A terminal role-player invents a secret conspiracy for fun, becomes absurdly powerful, and never realizes that his improvised fantasy is completely real.',
    coreFantasy: 'Perform the coolest mysterious mastermind imaginable while reality bends itself into proof that every dramatic line was correct.',
    pillars: ['secret mastermind role-play', 'overpowered spectacle', 'dramatic irony', 'hidden organization', 'genre parody'],
    motivations: ['self-aware power fantasy', 'dark comedy', 'stylish action', 'dramatic irony'],
    themes: ['performance', 'identity', 'power', 'fiction becoming real', 'obsession'],
    emotions: ['hype', 'ridiculous', 'darkly funny', 'stylish', 'chaotic'],
    atmosphere: ['gothic academies', 'underground bases', 'moonlit cities', 'theatrical battlefields'],
    vibes: { action: 9, comedy: 9, fantasy: 9, dark: 7, chaos: 8 },
    pacing: 'conspiracy arcs driven by the gap between the hero and everyone else',
    followUps: ['overlord', 'konosuba', 'one-punch-man', 'cautious-hero'],
    avoid: 'Skip if harem framing, edgelord performance, or deliberate misunderstanding comedy irritates you.'
  }),
  goldCard({
    id: 'ascendance-of-a-bookworm',
    titles: ['Ascendance of a Bookworm'],
    aliases: ['Honzuki no Gekokujou'],
    domain: 'knowledge-driven social progression',
    signature: 'A book-loving girl reborn into poverty uses craft knowledge, stubbornness, and social negotiation to make reading possible in a rigid medieval world.',
    coreFantasy: 'Rebuild access to knowledge from raw materials upward and change society through patient, practical invention.',
    pillars: ['craft progression', 'bookmaking', 'class constraints', 'family bonds', 'institutional negotiation'],
    motivations: ['visible invention progress', 'worldbuilding', 'competent heroine', 'slow social ascent'],
    themes: ['knowledge', 'class', 'family', 'access', 'adaptation'],
    emotions: ['cozy', 'curious', 'determined', 'frustrated', 'rewarding'],
    atmosphere: ['medieval workshops', 'market streets', 'small family home', 'temple libraries'],
    vibes: { fantasy: 8, mastery: 10, wholesome: 8, political: 6, emotional: 7 },
    pacing: 'deliberate project-by-project advancement with expanding institutions',
    complexity: 8,
    followUps: ['dr-stone', 'spice-and-wolf', 'the-apothecary-diaries', 'log-horizon'],
    avoid: 'Skip if slow progression, economic detail, or limited early action does not engage you.'
  }),
  goldCard({
    id: 'eighty-six',
    titles: ['86 EIGHTY-SIX'],
    aliases: ['86', 'Eighty-Six', '86 Eighty Six'],
    domain: 'war mecha discrimination drama',
    signature: 'A remote commander and a disposable squad confront a state built on dehumanization while voices across a battlefield create an intimate, impossible bond.',
    coreFantasy: 'Reach across a system designed to erase people and fight to have their names, lives, and sacrifices recognized.',
    pillars: ['remote battlefield bond', 'institutional racism', 'mecha warfare', 'survivor trauma', 'earned reunion'],
    motivations: ['war drama', 'political stakes', 'emotional connection', 'tactical action'],
    themes: ['dehumanization', 'memory', 'survival', 'responsibility', 'hope'],
    emotions: ['tense', 'angry', 'grieving', 'intimate', 'cathartic'],
    atmosphere: ['sterile capital', 'ruined battlefields', 'radio conversations', 'abandoned cities'],
    vibes: { action: 8, emotional: 10, dark: 9, political: 9, scifi: 9 },
    pacing: 'mission-driven war arcs with quiet relationship and trauma aftermath',
    complexity: 9,
    followUps: ['code-geass', 'attack-on-titan', 'mobile-suit-gundam-iron-blooded-orphans', 'vivy-fluorite-eyes-song'],
    avoid: 'Skip if racism, child soldiers, battlefield death, or trauma are unsafe themes.'
  }),
  goldCard({
    id: 'legend-of-the-galactic-heroes',
    titles: ['Legend of the Galactic Heroes'],
    aliases: ['LOGH', 'Ginga Eiyuu Densetsu'],
    domain: 'galactic political military epic',
    signature: 'Two strategic geniuses reshape rival interstellar governments while history, ideology, logistics, and ordinary lives complicate every clean story about heroism.',
    coreFantasy: 'Command fleets at the hinge of history and test whether democracy, enlightened autocracy, or human ambition can survive power.',
    pillars: ['grand strategy', 'political philosophy', 'rival commanders', 'historical narration', 'massive ensemble'],
    motivations: ['political complexity', 'military strategy', 'long-form epic', 'ideological debate'],
    themes: ['democracy', 'autocracy', 'history', 'ambition', 'war'],
    emotions: ['cerebral', 'majestic', 'tense', 'tragic', 'reflective'],
    atmosphere: ['vast fleet formations', 'imperial palaces', 'democratic chambers', 'history-documentary interludes'],
    vibes: { political: 10, scifi: 10, complexity: 10, action: 7, emotional: 8 },
    pacing: 'deliberate multi-year campaign history with dense political consequences',
    complexity: 10,
    followUps: ['monster', 'code-geass', 'mobile-suit-gundam', 'kingdom'],
    avoid: 'Skip if older production, enormous cast, long runtime, or dialogue-heavy politics are barriers.'
  }),
  goldCard({
    id: 'golden-kamuy',
    titles: ['Golden Kamuy'],
    domain: 'historical survival treasure hunt',
    signature: 'A veteran and an Ainu girl chase stolen gold through Hokkaido, mixing survival craft, indigenous culture, military conspiracy, grotesque villains, and fearless comedy.',
    coreFantasy: 'Cross a lethal frontier with a capable partner, reading land and people better than the armies and criminals hunting you.',
    pillars: ['treasure hunt', 'Ainu knowledge', 'survival craft', 'faction intrigue', 'tonal audacity'],
    motivations: ['historical adventure', 'eccentric ensemble', 'survival knowledge', 'unpredictable comedy'],
    themes: ['culture', 'survival', 'greed', 'war trauma', 'partnership'],
    emotions: ['adventurous', 'funny', 'brutal', 'curious', 'tense'],
    atmosphere: ['snowy Hokkaido', 'frontier villages', 'military prisons', 'wilderness camps'],
    vibes: { adventure: 10, comedy: 8, action: 8, historical: 10, chaos: 8 },
    pacing: 'fast faction pursuit with food, culture, and character detours',
    complexity: 8,
    followUps: ['vinland-saga', 'samurai-champloo', 'dororo', 'bungo-stray-dogs'],
    avoid: 'Skip if gore, crude humor, tonal whiplash, or historical violence are dealbreakers.'
  }),
  goldCard({
    id: 'bungo-stray-dogs',
    titles: ['Bungo Stray Dogs'],
    aliases: ['Bungou Stray Dogs'],
    domain: 'literary superpower faction drama',
    signature: 'Gifted detectives, mafia operatives, and international conspirators turn literary identities into stylish powers, shifting alliances, and trauma-shaped belonging.',
    coreFantasy: 'Join an eccentric agency where your dangerous gift can become useful and your found family will meet rival masterminds beside you.',
    pillars: ['literary abilities', 'faction conflict', 'found-family agency', 'mastermind games', 'stylish action'],
    motivations: ['large character roster', 'supernatural intrigue', 'rival organizations', 'stylish drama'],
    themes: ['belonging', 'purpose', 'trauma', 'morality', 'identity'],
    emotions: ['stylish', 'funny', 'dark', 'clever', 'loyal'],
    atmosphere: ['Yokohama streets', 'detective office', 'mafia towers', 'decadent underground spaces'],
    vibes: { action: 8, mystery: 8, comedy: 6, dark: 7, psychological: 7 },
    pacing: 'case and faction arcs that expand into layered conspiracies',
    followUps: ['durara', 'kekkai-sensen', 'golden-kamuy', 'moriarty-the-patriot'],
    avoid: 'Skip if tonal switching, literary references, or elaborate mastermind reversals frustrate you.'
  }),
  goldCard({
    id: 'higurashi',
    titles: ['Higurashi: When They Cry'],
    aliases: ['Higurashi no Naku Koro ni', 'When They Cry'],
    domain: 'rural time-loop paranoia horror',
    signature: 'A cheerful village summer repeatedly fractures into suspicion and murder until looping perspectives reveal a larger tragedy and the possibility of trust.',
    coreFantasy: 'Solve a nightmare that resets around your closest friends and learn whether understanding can break a fate built from paranoia.',
    pillars: ['time-loop mystery', 'unreliable perspectives', 'village conspiracy', 'friendship under pressure', 'graphic horror'],
    motivations: ['mystery reconstruction', 'psychological horror', 'long-form payoff', 'tragic friendship'],
    themes: ['trust', 'paranoia', 'fate', 'abuse', 'community'],
    emotions: ['cozy', 'suspicious', 'terrifying', 'tragic', 'hopeful'],
    atmosphere: ['rural summer', 'festival nights', 'isolated homes', 'forested shrines'],
    vibes: { horror: 10, mystery: 10, psychological: 10, dark: 10, emotional: 8 },
    pacing: 'repeating question arcs that become answer arcs and systemic revelation',
    complexity: 10,
    followUps: ['madoka-magica', 'steins-gate', 'shiki', 'summertime-rendering'],
    avoid: 'Skip if child abuse, torture, graphic violence, or extreme paranoia are unsafe.'
  }),
  goldCard({
    id: 'serial-experiments-lain',
    titles: ['Serial Experiments Lain'],
    aliases: ['Lain'],
    domain: 'network identity techno-psychology',
    signature: 'A quiet girl enters the Wired and watches boundaries between self, society, memory, divinity, and networked reality dissolve.',
    coreFantasy: 'Follow the internet past communication into a place where identity can be copied, rewritten, worshipped, or erased.',
    pillars: ['networked identity', 'reality instability', 'ambient dread', 'philosophical technology', 'fragmented perception'],
    motivations: ['experimental storytelling', 'techno-philosophy', 'psychological ambiguity', 'haunting atmosphere'],
    themes: ['identity', 'connection', 'memory', 'reality', 'godhood'],
    emotions: ['alienated', 'hypnotic', 'unsettling', 'lonely', 'transcendent'],
    atmosphere: ['empty suburbs', 'power-line hum', 'dark bedrooms', 'abstract network space'],
    vibes: { psychological: 10, experimental: 10, scifi: 9, mystery: 9, dark: 9 },
    pacing: 'slow, fragmented accumulation designed for interpretation rather than resolution speed',
    complexity: 10,
    followUps: ['neon-genesis-evangelion', 'texhnolyze', 'ghost-in-the-shell', 'monogatari-series'],
    avoid: 'Skip if abstraction, slow pacing, sparse exposition, or unresolved interpretation frustrate you.'
  }),
  goldCard({
    id: 'flcl',
    titles: ['FLCL'],
    aliases: ['Fooly Cooly'],
    domain: 'adolescent surreal rock explosion',
    signature: 'A bored boy collides with an alien woman, robots erupt from his head, and adolescent confusion becomes a six-episode blast of rock music and animation invention.',
    coreFantasy: 'Have ordinary adolescence cracked open by cosmic chaos until desire, maturity, and identity become impossible to ignore.',
    pillars: ['visual experimentation', 'rock soundtrack', 'coming-of-age metaphor', 'comic chaos', 'compressed emotion'],
    motivations: ['animation energy', 'surreal comedy', 'music-driven storytelling', 'dense rewatchable symbolism'],
    themes: ['adolescence', 'desire', 'maturity', 'identity', 'escape'],
    emotions: ['restless', 'funny', 'confused', 'electric', 'bittersweet'],
    atmosphere: ['sleepy suburb', 'industrial ruins', 'bedroom intimacy', 'cosmic ruptures'],
    vibes: { experimental: 10, chaos: 10, comedy: 8, scifi: 8, emotional: 7 },
    pacing: 'six episodes of compressed visual and musical escalation',
    complexity: 9,
    followUps: ['kill-la-kill', 'space-dandy', 'dandadan', 'neon-genesis-evangelion'],
    avoid: 'Skip if manic editing, sexual metaphor, or deliberate narrative opacity are hard limits.'
  }),
  goldCard({
    id: 'kill-la-kill',
    titles: ['Kill la Kill'],
    aliases: ['Kill La Kill'],
    domain: 'maximalist rebellion action satire',
    signature: 'A revenge-seeking transfer student fights a fascistic academy with a sentient uniform in a maximalist celebration of rebellion, body confidence, and chosen sisterhood.',
    coreFantasy: 'Turn shame into power and overthrow an absurd hierarchy through total commitment, impossible animation, and found family.',
    pillars: ['maximalist action', 'rebellion', 'sentient uniforms', 'sisterhood', 'visual satire'],
    motivations: ['hyperactive action', 'bold comedy', 'rebellious energy', 'animation spectacle'],
    themes: ['shame', 'freedom', 'family', 'authoritarianism', 'self-acceptance'],
    emotions: ['hype', 'ridiculous', 'defiant', 'funny', 'triumphant'],
    atmosphere: ['monumental academy', 'slums', 'fashion battlefields', 'cosmic finale'],
    vibes: { action: 10, chaos: 10, comedy: 9, emotional: 7, experimental: 8 },
    pacing: 'near-continuous escalation that repeatedly reinvents its stakes',
    followUps: ['flcl', 'gurren-lagann', 'promare', 'dandadan'],
    avoid: 'Skip if nudity, fan service, shouting, or relentless visual intensity are dealbreakers.'
  }),
  goldCard({
    id: 'lycoris-recoil',
    titles: ['Lycoris Recoil'],
    aliases: ['LycoReco'],
    domain: 'girls-with-guns found-family thriller',
    signature: 'A relentlessly cheerful elite agent and a serious displaced partner run a cafe while covert violence, state control, and mortality test their chosen life together.',
    coreFantasy: 'Balance secret-agent competence with a warm ordinary life and choose the person beside you over the system that made you useful.',
    pillars: ['female partnership', 'stylish gunplay', 'cafe found family', 'state conspiracy', 'life-affirming heroine'],
    motivations: ['character chemistry', 'accessible action', 'found-family warmth', 'light thriller tension'],
    themes: ['choice', 'mortality', 'friendship', 'institutional control', 'ordinary happiness'],
    emotions: ['bright', 'playful', 'tense', 'tender', 'hopeful'],
    atmosphere: ['cozy cafe', 'modern Tokyo', 'secret operations rooms', 'sunlit city walks'],
    vibes: { action: 8, wholesome: 8, emotional: 7, mystery: 6, comedy: 6 },
    pacing: 'episodic cafe missions that converge into a personal conspiracy climax',
    followUps: ['vivy-fluorite-eyes-song', 'buddy-daddies', 'princess-principal', 'spy-x-family'],
    avoid: 'Skip if implausible gunplay or a lighter treatment of covert violence bothers you.'
  })
];
