const fs = require('fs');
const path = require('path');

function findRoot(start) {
  let dir = start;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'package.json')) && fs.existsSync(path.join(dir, 'src'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith('.js')) out.push(full);
  }
  return out;
}

function toImportPath(fromFile, targetFile) {
  let rel = path.relative(path.dirname(fromFile), targetFile).replaceAll(path.sep, '/');
  rel = rel.replace(/\.js$/, '');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

function detectExports(fileText) {
  const matches = [...fileText.matchAll(/export\s+const\s+([A-Z0-9_]+)\s*=/g)];
  return matches.map((m) => m[1]).filter((name) =>
    name.includes('CARDS') ||
    name.includes('PACK') ||
    name.includes('GENOME') ||
    name.includes('MODULE')
  );
}

const root = findRoot(process.cwd());
const genomeDir = path.join(root, 'src', 'ai', 'genome');
const registryFile = path.join(genomeDir, 'genomeRegistry.js');

const sources = [
  path.join(genomeDir, 'core25'),
  path.join(genomeDir, 'enhanced'),
  path.join(genomeDir, 'core100'),
  path.join(genomeDir, 'generated'),
  path.join(root, 'src', 'ai', 'modules')
];

const packFiles = sources
  .flatMap(walk)
  .filter((file) => !file.endsWith('genomeRegistry.js'))
  // SPRINT8_SKIP_MODULE_INDEX
  // Module index exports an array of modules, not cards. Individual module files expose module.cards.
  .filter((file) => !file.replaceAll(path.sep, '/').endsWith('src/ai/modules/index.js'));

const imports = [];
const spreads = [];
const warnings = [];

packFiles.forEach((file, index) => {
  const text = fs.readFileSync(file, 'utf8');
  const exports = detectExports(text);

  if (!exports.length) {
    warnings.push(`No export detected in ${path.relative(root, file)}`);
    return;
  }

  const importName = `pack${index}`;
  imports.push(`import * as ${importName} from '${toImportPath(registryFile, file)}';`);

  for (const exportName of exports) {
    spreads.push(`  ...normalizePack(${importName}.${exportName}, '${path.relative(root, file).replaceAll(path.sep, '/')}#${exportName}'),`);
  }
});

function mergeGenomeCardsByPrioritySnippet() {
  return `function mergeGenomeCardsByPriority(...groups) {
  const byId = new Map();

  for (const group of groups) {
    for (const card of group || []) {
      if (!card?.id) continue;
      if (!byId.has(card.id)) byId.set(card.id, card);
    }
  }

  return [...byId.values()];
}

`;
}

const output = `// AUTO-GENERATED by scripts/rebuildGenomeRegistry.cjs
// Do not hand-edit. Add files under src/ai/genome/gold, core25, core100, enhanced, or generated,
// then run: node scripts/rebuildGenomeRegistry.cjs

${imports.join('\n')}\n${mergeGenomeCardsByPrioritySnippet()}import { GOLD_STANDARD_GENOME_CARDS } from './gold/goldStandardGenomeCards';\nimport { buildAliasIndex, cardMatchesTitle, canonicalAnimeId, normalizeAnimeTitle } from '../titleAliases';

export const GENOME_REGISTRY_VERSION = '0.2.0';

function normalizePack(value, source) {
  if (!value) return [];

  if (Array.isArray(value)) {
    // SPRINT8_ARRAY_CARD_GUARD
    // Only arrays of actual cards belong in the registry.
    return value
      .filter((card) => card && card.id && (card.titles || card.title || card.signature || card.domain))
      .map((card) => ({ ...card, registrySource: card.registrySource || source }));
  }

  // Sprint 8 Knowledge Modules expose cards under module.cards.
  if (value.cards && Array.isArray(value.cards)) {
    return value.cards.map((card) => ({
      ...card,
      moduleId: value.id,
      moduleName: value.name,
      registrySource: card.registrySource || source,
      joeNote: value.joeNotes?.[card.id] || card.joeNote
    }));
  }

  return [];
}

const RAW_GENOME_REGISTRY = [
${spreads.join('\n')}
];

const seen = new Set();
const duplicateIds = [];

export const ACTIVE_GENOME_REGISTRY = RAW_GENOME_REGISTRY.filter((card) => {
  if (!card || !card.id) return false;
  if (seen.has(card.id)) {
    duplicateIds.push(card.id);
    return false;
  }
  seen.add(card.id);
  return true;
});

export const GENOME_REGISTRY = ACTIVE_GENOME_REGISTRY;

export const GENOME_ALIAS_INDEX = buildAliasIndex(ACTIVE_GENOME_REGISTRY || []);

function fallbackNormalize(value = '') {
  return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

export function findGenomeCardByTitle(animeOrTitle = '') {
  const searchText = typeof animeOrTitle === 'string'
    ? animeOrTitle
    : [
        animeOrTitle.title,
        animeOrTitle.officialTitle,
        animeOrTitle.titleEnglish,
        animeOrTitle.japaneseTitle,
        animeOrTitle.titleJapanese,
        ...(animeOrTitle.titleSynonyms || []),
        ...(animeOrTitle.aliases || [])
      ].filter(Boolean).join(' ');

  const direct =
    GENOME_ALIAS_INDEX.get(normalizeAnimeTitle(searchText)) ||
    GENOME_ALIAS_INDEX.get(canonicalAnimeId(searchText));

  if (direct) return direct;

  return ACTIVE_GENOME_REGISTRY.find((card) =>
    cardMatchesTitle(card, searchText) ||
    fallbackNormalize(searchText).includes(fallbackNormalize(card.id)) ||
    (card.titles || []).some((title) => {
      const cleanTitle = fallbackNormalize(title);
      const cleanSearch = fallbackNormalize(searchText);
      return cleanSearch.includes(cleanTitle) || cleanTitle.includes(cleanSearch);
    }) ||
    (card.aliases || []).some((alias) => {
      const cleanAlias = fallbackNormalize(alias);
      const cleanSearch = fallbackNormalize(searchText);
      return cleanSearch.includes(cleanAlias) || cleanAlias.includes(cleanSearch);
    })
  ) || null;
}

export function findGenomeCardFromRegistry(animeOrTitle = '') {
  return findGenomeCardByTitle(animeOrTitle);
}

export function getGenomeRegistryStats() {
  return {
    version: GENOME_REGISTRY_VERSION,
    totalRaw: RAW_GENOME_REGISTRY.length,
    totalActive: ACTIVE_GENOME_REGISTRY.length,
    duplicatesRemoved: duplicateIds.length,
    duplicateIds
  };
}
`;

fs.writeFileSync(registryFile, output, 'utf8');

console.log('');
console.log('========================================');
console.log(' JoeAI Genome Registry Builder');
console.log('========================================');
console.log(`Pack files found:      ${packFiles.length}`);
console.log(`Imports generated:     ${imports.length}`);
console.log(`Registry file:         ${path.relative(root, registryFile)}`);
console.log('');

if (warnings.length) {
  console.log('Warnings:');
  warnings.forEach((w) => console.log(' - ' + w));
  console.log('');
}

console.log('Registry rebuilt successfully.');
console.log('');
