const fs = require('fs');
const path = require('path');

function findRoot(start) {
  let dir = start;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'package.json')) && fs.existsSync(path.join(dir, 'src'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}
function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith('.js')) out.push(full);
  }
  return out;
}
function toImportPath(fromFile, targetFile) {
  let rel = path.relative(path.dirname(fromFile), targetFile).replaceAll(path.sep, '/');
  rel = rel.replace(/\.js$/, '');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

function relFromRoot(root, file) {
  return path.relative(root, file).replaceAll(path.sep, '/');
}

function detectExports(fileText) {
  const names = [...fileText.matchAll(/export\s+const\s+([A-Za-z0-9_]+)\s*=/g)]
    .map((m) => m[1]);
  return names.filter((name) => {
    const upper = name.toUpperCase();
    return upper.includes('CARDS') || upper.includes('PACK') || upper.includes('GENOME') || upper.includes('MODULE');
  });
}

const root = findRoot(process.cwd());
const genomeDir = path.join(root, 'src', 'ai', 'genome');
const registryFile = path.join(genomeDir, 'genomeRegistry.js');
const registryTiers = [
  { id: 'gold', directory: path.join(genomeDir, 'gold') },
  { id: 'core25', directory: path.join(genomeDir, 'core25') },
  { id: 'enhanced', directory: path.join(genomeDir, 'enhanced') },
  { id: 'core100', directory: path.join(genomeDir, 'core100') },
  { id: 'generated', directory: path.join(genomeDir, 'generated') },
  { id: 'modules', directory: path.join(root, 'src', 'ai', 'modules') },
];

const sources = registryTiers.map((tier) => tier.directory);
function tierForFile(file) {
  return registryTiers.find((tier) => file.startsWith(tier.directory + path.sep))?.id || 'modules';
}
const packFiles = sources
  .flatMap(walk)
  .filter((file) => !file.endsWith('genomeRegistry.js'))
  .filter((file) => !relFromRoot(root, file).endsWith('src/ai/modules/index.js'))
  .sort((a, b) => {
    const ra = relFromRoot(root, a);
    const rb = relFromRoot(root, b);
    const priority = (rel) => registryTiers.findIndex((tier) => rel.includes(`/${tier.id}/`));
    return priority(ra) - priority(rb) || ra.localeCompare(rb);
  });

const imports = [];
const spreads = [];
const warnings = [];
packFiles.forEach((file, index) => {
  const text = fs.readFileSync(file, 'utf8');
  const exports = detectExports(text);

  if (!exports.length) {
    warnings.push(`No registry export detected in ${relFromRoot(root, file)}`);
    return;
  }

  const importName = `pack${index}`;
  const tier = tierForFile(file);
  imports.push(`import * as ${importName} from '${toImportPath(registryFile, file)}';`);
  for (const exportName of exports) {
    spreads.push(`  ...normalizePack(${importName}.${exportName}, '${relFromRoot(root, file)}#${exportName}', '${tier}'),`);
  }
});

const output = `// AUTO-GENERATED by scripts/rebuildGenomeRegistry.cjs
// Do not hand-edit.
// Add files under src/ai/genome/gold, core25, core100, enhanced, generated, or src/ai/modules,
// then run: node scripts/rebuildGenomeRegistry.cjs
${imports.join('\n')}
import { buildAliasIndex, cardMatchesTitle, canonicalAnimeId, normalizeAnimeTitle } from '../titleAliases';

export const GENOME_REGISTRY_VERSION = '0.3.0';
export const GENOME_REGISTRY_PRECEDENCE = Object.freeze(${JSON.stringify(registryTiers.map((tier) => tier.id))});

function normalizePack(value, source, tier) {
  if (!value) return [];
  if (Array.isArray(value)) {
    return value
      .filter((card) => card && card.id && (card.titles || card.title || card.signature || card.domain))
      .map((card) => ({
        ...card,
        registrySource: card.registrySource || source,
        registryTier: card.registryTier || tier,
      }));
  }
  if (value.cards && Array.isArray(value.cards)) {
    return value.cards.map((card) => ({
      ...card,
      moduleId: value.id,
      moduleName: value.name,
      registrySource: card.registrySource || source,
      registryTier: card.registryTier || tier,
      joeNote: value.joeNotes?.[card.id] || card.joeNote,
    }));
  }

  return [];
}

const RAW_GENOME_REGISTRY = [
${spreads.join('\n')}
];

const seen = new Set();
const duplicateIds = [];
export const ACTIVE_GENOME_REGISTRY = RAW_GENOME_REGISTRY.filter((card) => {
  if (!card || !card.id) return false;
  if (seen.has(card.id)) {
    duplicateIds.push(card.id);
    return false;
  }
  seen.add(card.id);
  return true;
});

export const GENOME_REGISTRY = ACTIVE_GENOME_REGISTRY;
export const GENOME_ALIAS_INDEX = buildAliasIndex(ACTIVE_GENOME_REGISTRY || []);

function fallbackNormalize(value = '') {
  return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function fallbackContainsMatch(searchText = '', candidate = '') {
  const cleanSearch = fallbackNormalize(searchText);
  const cleanCandidate = fallbackNormalize(candidate);
  if (!cleanSearch || !cleanCandidate) return false;
  if (cleanSearch === cleanCandidate) return true;
  if (Math.min(cleanSearch.length, cleanCandidate.length) < 4) return false;
  return cleanSearch.includes(cleanCandidate) || cleanCandidate.includes(cleanSearch);
}

export function findGenomeCardByTitle(animeOrTitle = '') {
  const searchText = typeof animeOrTitle === 'string'
    ? animeOrTitle
    : [
        animeOrTitle.title,
        animeOrTitle.officialTitle,
        animeOrTitle.titleEnglish,
        animeOrTitle.japaneseTitle,
        animeOrTitle.titleJapanese,
        ...(animeOrTitle.titleSynonyms || []),
        ...(animeOrTitle.aliases || []),
      ].filter(Boolean).join(' ');
  const direct = GENOME_ALIAS_INDEX.get(normalizeAnimeTitle(searchText))
    || GENOME_ALIAS_INDEX.get(canonicalAnimeId(searchText));

  if (direct) return direct;
  return ACTIVE_GENOME_REGISTRY.find((card) =>
    cardMatchesTitle(card, searchText)
    || fallbackContainsMatch(searchText, card.id)
    || (card.titles || []).some((title) => fallbackContainsMatch(searchText, title))
    || (card.aliases || []).some((alias) => fallbackContainsMatch(searchText, alias))
  ) || null;
}
export function findGenomeCardFromRegistry(animeOrTitle = '') {
  return findGenomeCardByTitle(animeOrTitle);
}

export function getGenomeRegistryStats() {
  const activeByTier = ACTIVE_GENOME_REGISTRY.reduce((counts, card) => {
    const tier = card.registryTier || 'unknown';
    counts[tier] = (counts[tier] || 0) + 1;
    return counts;
  }, {});
  return {
    version: GENOME_REGISTRY_VERSION,
    precedence: [...GENOME_REGISTRY_PRECEDENCE],
    totalRaw: RAW_GENOME_REGISTRY.length,
    totalActive: ACTIVE_GENOME_REGISTRY.length,
    activeByTier,
    duplicatesRemoved: duplicateIds.length,
    duplicateIds,
  };
}
`;

fs.writeFileSync(registryFile, output, 'utf8');
console.log('');
console.log('========================================');
console.log(' JoeAI Genome Registry Builder v0.3.0');
console.log('========================================');
console.log(`Pack files found:     ${packFiles.length}`);
console.log(`Imports generated:   ${imports.length}`);
console.log(`Registry file:       ${relFromRoot(root, registryFile)}`);
console.log('');

if (warnings.length) {
  console.log('Warnings:');
  warnings.forEach((w) => console.log(' - ' + w));
  console.log('');
}
const registryText = fs.readFileSync(registryFile, 'utf8');
const goldPack2Detected = registryText.includes('goldStandardGenomeCardsPack2')
  || registryText.includes('GOLD_STANDARD_GENOME_CARDS_PACK_2');

console.log(goldPack2Detected ? '[ok] Gold Pack 2 detected in registry.' : '[warn] Gold Pack 2 was not detected. Check that the file is in src/ai/genome/gold.');
console.log('Registry rebuilt successfully.');
console.log('');
