// Sprint 5 Core 100 Genome Pack v1
// 100 identity-first starter Genome Cards.
// These are intentionally concise v1 cards. We will deepen them over time.

export const CORE100_VERSION = '0.1.0';

export const CORE100_GENOME_CARDS = [
  {
    id: 'bleach',
    titles: ['Bleach'],
    franchiseId: 'bleach',
    domain: 'supernatural battle shonen',
    subdomain: 'sword-based spirit combat',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Pure style, swords, spiritual warfare, and unforgettable power reveals.'
  },
  {
    id: 'naruto',
    titles: ['Naruto'],
    franchiseId: 'naruto',
    domain: 'ninja battle shonen',
    subdomain: 'underdog rivalry progression',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['ninja'],
    avoidDomains: [],
    successors: [],
    note: 'A long-form story about loneliness, rivalry, friendship, and refusing to give up.'
  },
  {
    id: 'one-piece',
    titles: ['One Piece'],
    franchiseId: 'one-piece',
    domain: 'adventure shonen',
    subdomain: 'pirate worldbuilding',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['adventure'],
    avoidDomains: [],
    successors: [],
    note: 'A massive adventure about freedom, found family, dreams, and a world that keeps expanding.'
  },
  {
    id: 'dragon-ball-z',
    titles: ['Dragon Ball Z'],
    franchiseId: 'dragon-ball-z',
    domain: 'battle shonen',
    subdomain: 'martial arts power escalation',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['battle'],
    avoidDomains: [],
    successors: [],
    note: 'The blueprint for power-ups, transformations, rivalries, and planet-shaking fights.'
  },
  {
    id: 'hunter-x-hunter',
    titles: ['Hunter x Hunter'],
    franchiseId: 'hunter-x-hunter',
    domain: 'adventure battle shonen',
    subdomain: 'strategic power-system storytelling',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['adventure'],
    avoidDomains: [],
    successors: [],
    note: 'A deceptively playful adventure that becomes one of anime\'s smartest power-system stories.'
  },
  {
    id: 'fullmetal-alchemist-brotherhood',
    titles: ['Fullmetal Alchemist: Brotherhood'],
    franchiseId: 'fullmetal-alchemist-brotherhood',
    domain: 'fantasy adventure',
    subdomain: 'alchemy political epic',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['fantasy'],
    avoidDomains: [],
    successors: [],
    note: 'A tightly written adventure about sacrifice, family, war, truth, and the cost of power.'
  },
  {
    id: 'attack-on-titan',
    titles: ['Attack on Titan'],
    franchiseId: 'attack-on-titan',
    domain: 'dark action mystery',
    subdomain: 'military survival conspiracy',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A brutal survival story that evolves into war, politics, trauma, and moral collapse.'
  },
  {
    id: 'death-note',
    titles: ['Death Note'],
    franchiseId: 'death-note',
    domain: 'psychological thriller',
    subdomain: 'cat-and-mouse mind games',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['psychological'],
    avoidDomains: [],
    successors: [],
    note: 'A ruthless battle of intellect, ego, justice, and manipulation.'
  },
  {
    id: 'code-geass',
    titles: ['Code Geass'],
    franchiseId: 'code-geass',
    domain: 'mecha political thriller',
    subdomain: 'revolution chessmaster drama',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mecha'],
    avoidDomains: [],
    successors: [],
    note: 'A stylish rebellion story built on strategy, betrayal, power, and impossible choices.'
  },
  {
    id: 'jujutsu-kaisen',
    titles: ['Jujutsu Kaisen'],
    franchiseId: 'jujutsu-kaisen',
    domain: 'supernatural battle shonen',
    subdomain: 'curse combat',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Modern supernatural action with brutal fights, style, curses, and emotional damage.'
  },
  {
    id: 'chainsaw-man',
    titles: ['Chainsaw Man'],
    franchiseId: 'chainsaw-man',
    domain: 'dark action',
    subdomain: 'devil horror black comedy',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'Violent, funny, tragic, gross, and weirdly human.'
  },
  {
    id: 'demon-slayer',
    titles: ['Demon Slayer'],
    franchiseId: 'demon-slayer',
    domain: 'supernatural sword shonen',
    subdomain: 'demon hunting emotional spectacle',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'A beautiful, emotional demon-hunting story with clean arcs and spectacular fights.'
  },
  {
    id: 'black-clover',
    titles: ['Black Clover'],
    franchiseId: 'black-clover',
    domain: 'magic battle shonen',
    subdomain: 'loud underdog power growth',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['magic'],
    avoidDomains: [],
    successors: [],
    note: 'A loud, earnest underdog climb through magic squads, rivalry, and hype battles.'
  },
  {
    id: 'my-hero-academia',
    titles: ['My Hero Academia'],
    franchiseId: 'my-hero-academia',
    domain: 'superhero battle shonen',
    subdomain: 'school hero progression',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['superhero'],
    avoidDomains: [],
    successors: [],
    note: 'A superhero coming-of-age story about legacy, ideals, and learning what heroism costs.'
  },
  {
    id: 'yu-yu-hakusho',
    titles: ['Yu Yu Hakusho'],
    franchiseId: 'yu-yu-hakusho',
    domain: 'supernatural battle shonen',
    subdomain: 'spirit detective tournament',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Classic supernatural fights with attitude, heart, and one of anime\'s best tournament arcs.'
  },
  {
    id: 'jojo',
    titles: ['JoJo\'s Bizarre Adventure'],
    franchiseId: 'jojo',
    domain: 'stylized action',
    subdomain: 'generational supernatural weirdness',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['stylized'],
    avoidDomains: [],
    successors: [],
    note: 'Generational chaos, fabulous poses, strange powers, and pure anime excess.'
  },
  {
    id: 'solo-leveling',
    titles: ['Solo Leveling'],
    franchiseId: 'solo-leveling',
    domain: 'power fantasy action',
    subdomain: 'overpowered hunter progression',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['power'],
    avoidDomains: [],
    successors: [],
    note: 'A sleek power fantasy about leveling from weakest hunter to unstoppable force.'
  },
  {
    id: 'mob-psycho-100',
    titles: ['Mob Psycho 100'],
    franchiseId: 'mob-psycho-100',
    domain: 'supernatural coming-of-age',
    subdomain: 'emotional psychic comedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'A hilarious and heartfelt story about power, emotions, and becoming a better person.'
  },
  {
    id: 'one-punch-man',
    titles: ['One Punch Man'],
    franchiseId: 'one-punch-man',
    domain: 'superhero parody action',
    subdomain: 'overpowered comedy satire',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['superhero'],
    avoidDomains: [],
    successors: [],
    note: 'A superhero action comedy about being too strong to enjoy the game anymore.'
  },
  {
    id: 'fairy-tail',
    titles: ['Fairy Tail'],
    franchiseId: 'fairy-tail',
    domain: 'guild fantasy shonen',
    subdomain: 'friendship magic adventure',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['guild'],
    avoidDomains: [],
    successors: [],
    note: 'A friendship-heavy magic guild adventure built on loyalty, emotion, and big attacks.'
  },
  {
    id: 'dorohedoro',
    titles: ['Dorohedoro'],
    franchiseId: 'dorohedoro',
    domain: 'dark fantasy',
    subdomain: 'urban body horror chaos',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'Dirty, violent, hilarious, grotesque, and somehow lovable.'
  },
  {
    id: 'berserk',
    titles: ['Berserk'],
    franchiseId: 'berserk',
    domain: 'dark fantasy',
    subdomain: 'tragic medieval brutality',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A brutal, tragic dark fantasy about ambition, trauma, fate, and survival.'
  },
  {
    id: 'vinland-saga',
    titles: ['Vinland Saga'],
    franchiseId: 'vinland-saga',
    domain: 'historical seinen',
    subdomain: 'revenge to pacifism epic',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['historical'],
    avoidDomains: [],
    successors: [],
    note: 'A Viking revenge story that becomes a profound meditation on violence and freedom.'
  },
  {
    id: 'monster',
    titles: ['Monster'],
    franchiseId: 'monster',
    domain: 'psychological thriller',
    subdomain: 'slow-burn moral horror',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['psychological'],
    avoidDomains: [],
    successors: [],
    note: 'A slow, grounded masterpiece about evil, guilt, identity, and moral responsibility.'
  },
  {
    id: 'parasyte',
    titles: ['Parasyte: The Maxim'],
    franchiseId: 'parasyte',
    domain: 'sci-fi horror',
    subdomain: 'body invasion identity crisis',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sci-fi'],
    avoidDomains: [],
    successors: [],
    note: 'Body horror and alien invasion used to explore humanity, survival, and empathy.'
  },
  {
    id: 'tokyo-ghoul',
    titles: ['Tokyo Ghoul'],
    franchiseId: 'tokyo-ghoul',
    domain: 'dark urban fantasy',
    subdomain: 'monster identity tragedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A tragic urban monster story about identity, hunger, trauma, and losing yourself.'
  },
  {
    id: 'hells-paradise',
    titles: ['Hell\'s Paradise'],
    franchiseId: 'hells-paradise',
    domain: 'dark fantasy action',
    subdomain: 'body-horror island survival',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'Violent fantasy survival with strange powers, moral grayness, and a dangerous mystery.'
  },
  {
    id: 'made-in-abyss',
    titles: ['Made in Abyss'],
    franchiseId: 'made-in-abyss',
    domain: 'dark adventure',
    subdomain: 'beautiful horror exploration',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A beautiful adventure that gets more horrifying the deeper it goes.'
  },
  {
    id: 'golden-kamuy',
    titles: ['Golden Kamuy'],
    franchiseId: 'golden-kamuy',
    domain: 'historical adventure',
    subdomain: 'violent survival comedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['historical'],
    avoidDomains: [],
    successors: [],
    note: 'A violent, bizarre, hilarious treasure hunt full of adult maniacs and survival detail.'
  },
  {
    id: 'black-lagoon',
    titles: ['Black Lagoon'],
    franchiseId: 'black-lagoon',
    domain: 'crime action',
    subdomain: 'mercenary underworld gunplay',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['crime'],
    avoidDomains: [],
    successors: [],
    note: 'Dirty gunfights, criminals, moral rot, and adults making bad choices.'
  },
  {
    id: 'claymore',
    titles: ['Claymore'],
    franchiseId: 'claymore',
    domain: 'dark fantasy',
    subdomain: 'monster-hunting warrior tragedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'Bleak monster-hunting fantasy about identity, warriors, and barely controlled power.'
  },
  {
    id: 'devilman-crybaby',
    titles: ['Devilman Crybaby'],
    franchiseId: 'devilman-crybaby',
    domain: 'apocalyptic horror',
    subdomain: 'violent tragedy morality collapse',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['apocalyptic'],
    avoidDomains: [],
    successors: [],
    note: 'A raw, brutal, emotional apocalypse about humanity devouring itself.'
  },
  {
    id: 'akudama-drive',
    titles: ['Akudama Drive'],
    franchiseId: 'akudama-drive',
    domain: 'cyberpunk action',
    subdomain: 'criminal suicide mission',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['cyberpunk'],
    avoidDomains: [],
    successors: [],
    note: 'Flashy cyberpunk criminals, chaos, violence, and a doomed mission.'
  },
  {
    id: 'psycho-pass',
    titles: ['Psycho-Pass'],
    franchiseId: 'psycho-pass',
    domain: 'cyberpunk thriller',
    subdomain: 'surveillance crime philosophy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['cyberpunk'],
    avoidDomains: [],
    successors: [],
    note: 'A cyberpunk police thriller about justice, free will, and state control.'
  },
  {
    id: 'ergo-proxy',
    titles: ['Ergo Proxy'],
    franchiseId: 'ergo-proxy',
    domain: 'philosophical sci-fi',
    subdomain: 'post-apocalyptic identity mystery',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['philosophical'],
    avoidDomains: [],
    successors: [],
    note: 'Dense philosophical sci-fi about identity, memory, and ruined worlds.'
  },
  {
    id: 'texhnolyze',
    titles: ['Texhnolyze'],
    franchiseId: 'texhnolyze',
    domain: 'nihilistic sci-fi',
    subdomain: 'industrial despair slow burn',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['nihilistic'],
    avoidDomains: [],
    successors: [],
    note: 'Bleak, punishing, atmospheric sci-fi for maximum existential dread.'
  },
  {
    id: 'ghost-in-the-shell',
    titles: ['Ghost in the Shell'],
    franchiseId: 'ghost-in-the-shell',
    domain: 'cyberpunk sci-fi',
    subdomain: 'identity consciousness politics',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['cyberpunk'],
    avoidDomains: [],
    successors: [],
    note: 'Cyberpunk identity, philosophy, surveillance, and what it means to be human.'
  },
  {
    id: 'cowboy-bebop',
    titles: ['Cowboy Bebop'],
    franchiseId: 'cowboy-bebop',
    domain: 'space western',
    subdomain: 'melancholy bounty hunter jazz',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['space'],
    avoidDomains: [],
    successors: [],
    note: 'Cool space bounty hunting wrapped around loneliness, regret, and jazz.'
  },
  {
    id: 'samurai-champloo',
    titles: ['Samurai Champloo'],
    franchiseId: 'samurai-champloo',
    domain: 'samurai road trip',
    subdomain: 'hip-hop historical adventure',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['samurai'],
    avoidDomains: [],
    successors: [],
    note: 'A stylish samurai road trip powered by hip-hop, sword fights, and wandering.'
  },
  {
    id: 'trigun',
    titles: ['Trigun'],
    franchiseId: 'trigun',
    domain: 'space western',
    subdomain: 'pacifist gunslinger tragedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['space'],
    avoidDomains: [],
    successors: [],
    note: 'A funny gunslinger adventure hiding a painful story about pacifism and survival.'
  },
  {
    id: 'evangelion',
    titles: ['Neon Genesis Evangelion'],
    franchiseId: 'evangelion',
    domain: 'psychological mecha',
    subdomain: 'trauma apocalypse symbolism',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['psychological'],
    avoidDomains: [],
    successors: [],
    note: 'Mecha, depression, apocalypse, identity collapse, and emotional damage.'
  },
  {
    id: 'gurren-lagann',
    titles: ['Gurren Lagann'],
    franchiseId: 'gurren-lagann',
    domain: 'super robot action',
    subdomain: 'spiral hype escalation',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['super'],
    avoidDomains: [],
    successors: [],
    note: 'Pure escalating hype about belief, brotherhood, impossible odds, and drilling through heaven.'
  },
  {
    id: 'steins-gate',
    titles: ['Steins;Gate'],
    franchiseId: 'steins-gate',
    domain: 'sci-fi thriller',
    subdomain: 'time travel emotional puzzle',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sci-fi'],
    avoidDomains: [],
    successors: [],
    note: 'A slow-starting time travel thriller that becomes devastating and brilliant.'
  },
  {
    id: 'code-geass-duplicate',
    titles: ['Code Geass'],
    franchiseId: 'code-geass-duplicate',
    domain: 'mecha political thriller',
    subdomain: 'revolution chessmaster drama',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mecha'],
    avoidDomains: [],
    successors: [],
    note: 'Strategy, rebellion, betrayal, charisma, and impossible choices.'
  },
  {
    id: 'redline',
    titles: ['Redline'],
    franchiseId: 'redline',
    domain: 'racing spectacle',
    subdomain: 'maximum velocity animation',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['racing'],
    avoidDomains: [],
    successors: [],
    note: 'Pure racing adrenaline, hand-drawn insanity, and speed as a religion.'
  },
  {
    id: 'initial-d',
    titles: ['Initial D'],
    franchiseId: 'initial-d',
    domain: 'motorsports',
    subdomain: 'touge street racing mastery',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['motorsports'],
    avoidDomains: [],
    successors: [],
    note: 'A quiet masterpiece about technical perfection disguised as a street racing anime.'
  },
  {
    id: 'mf-ghost',
    titles: ['MF Ghost'],
    franchiseId: 'mf-ghost',
    domain: 'motorsports',
    subdomain: 'street racing successor',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['motorsports'],
    avoidDomains: [],
    successors: [],
    note: 'The modern successor to Initial D\'s street-racing philosophy.'
  },
  {
    id: 'wangan-midnight',
    titles: ['Wangan Midnight'],
    franchiseId: 'wangan-midnight',
    domain: 'motorsports',
    subdomain: 'highway racing obsession',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['motorsports'],
    avoidDomains: [],
    successors: [],
    note: 'Night highway racing, dangerous obsession, and mechanical devotion.'
  },
  {
    id: 'capeta',
    titles: ['Capeta'],
    franchiseId: 'capeta',
    domain: 'motorsports',
    subdomain: 'racing career growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['motorsports'],
    avoidDomains: [],
    successors: [],
    note: 'Grounded racing progression focused on skill, ambition, and motorsport growth.'
  },
  {
    id: 'overtake',
    titles: ['Overtake!'],
    franchiseId: 'overtake',
    domain: 'motorsports',
    subdomain: 'professional racing drama',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['motorsports'],
    avoidDomains: [],
    successors: [],
    note: 'Motorsport pressure, emotional drama, and the cost of chasing speed.'
  },
  {
    id: 'haikyuu',
    titles: ['Haikyuu!!'],
    franchiseId: 'haikyuu',
    domain: 'sports',
    subdomain: 'volleyball team growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'A hype sports story about teamwork, growth, rivalry, and momentum.'
  },
  {
    id: 'blue-lock',
    titles: ['Blue Lock'],
    franchiseId: 'blue-lock',
    domain: 'sports',
    subdomain: 'ego-driven soccer survival',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'Soccer as ego warfare, striker obsession, and psychological competition.'
  },
  {
    id: 'hajime-no-ippo',
    titles: ['Hajime no Ippo'],
    franchiseId: 'hajime-no-ippo',
    domain: 'sports',
    subdomain: 'boxing underdog mastery',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'A boxing classic about training, courage, rivalries, and earning strength.'
  },
  {
    id: 'slam-dunk',
    titles: ['Slam Dunk'],
    franchiseId: 'slam-dunk',
    domain: 'sports',
    subdomain: 'basketball delinquent growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'Basketball, comedy, growth, and a delinquent finding purpose.'
  },
  {
    id: 'kuroko-no-basket',
    titles: ['Kuroko\'s Basketball'],
    franchiseId: 'kuroko-no-basket',
    domain: 'sports',
    subdomain: 'superpowered basketball rivalry',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'Stylized basketball with miracle-level rivals and shonen energy.'
  },
  {
    id: 'yuri-on-ice',
    titles: ['Yuri!!! on Ice'],
    franchiseId: 'yuri-on-ice',
    domain: 'sports',
    subdomain: 'figure skating emotional performance',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sports'],
    avoidDomains: [],
    successors: [],
    note: 'Figure skating, anxiety, romance-coded support, and performance pressure.'
  },
  {
    id: 'mushoku-tensei',
    titles: ['Mushoku Tensei'],
    franchiseId: 'mushoku-tensei',
    domain: 'isekai fantasy',
    subdomain: 'second-life character growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'A detailed fantasy reincarnation story about growth, flaws, and worldbuilding.'
  },
  {
    id: 'rezero',
    titles: ['Re:Zero'],
    franchiseId: 'rezero',
    domain: 'isekai psychological fantasy',
    subdomain: 'death-loop trauma mystery',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'Isekai suffering, time loops, trauma, mystery, and emotional collapse.'
  },
  {
    id: 'overlord',
    titles: ['Overlord'],
    franchiseId: 'overlord',
    domain: 'isekai dark fantasy',
    subdomain: 'villainous empire building',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'Overpowered undead ruler, dark comedy, conquest, and NPC loyalty.'
  },
  {
    id: 'slime',
    titles: ['That Time I Got Reincarnated as a Slime'],
    franchiseId: 'slime',
    domain: 'isekai nation building',
    subdomain: 'power fantasy community building',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'A cozy power fantasy about building a nation, making allies, and leveling up a world.'
  },
  {
    id: 'konosuba',
    titles: ['Konosuba'],
    franchiseId: 'konosuba',
    domain: 'isekai comedy',
    subdomain: 'useless party parody',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'A hilarious isekai parody about terrible party members and chaotic stupidity.'
  },
  {
    id: 'shield-hero',
    titles: ['The Rising of the Shield Hero'],
    franchiseId: 'shield-hero',
    domain: 'isekai revenge fantasy',
    subdomain: 'betrayal-to-power climb',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'Isekai betrayal, defensive power growth, and rebuilding trust.'
  },
  {
    id: 'log-horizon',
    titles: ['Log Horizon'],
    franchiseId: 'log-horizon',
    domain: 'isekai strategy',
    subdomain: 'MMO society building',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'MMO isekai focused on systems, politics, strategy, and community.'
  },
  {
    id: 'sao',
    titles: ['Sword Art Online'],
    franchiseId: 'sao',
    domain: 'VRMMO fantasy',
    subdomain: 'virtual survival romance action',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['VRMMO'],
    avoidDomains: [],
    successors: [],
    note: 'Virtual worlds, survival stakes, romance, and game-like power fantasy.'
  },
  {
    id: 'no-game-no-life',
    titles: ['No Game No Life'],
    franchiseId: 'no-game-no-life',
    domain: 'isekai games',
    subdomain: 'genius sibling strategy comedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['isekai'],
    avoidDomains: [],
    successors: [],
    note: 'Colorful game-world strategy with smug genius energy.'
  },
  {
    id: 'frieren',
    titles: ['Frieren: Beyond Journey\'s End'],
    franchiseId: 'frieren',
    domain: 'melancholy fantasy',
    subdomain: 'post-adventure reflection',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['melancholy'],
    avoidDomains: [],
    successors: [],
    note: 'A story about what happens after the heroes already saved the world.'
  },
  {
    id: 'violet-evergarden',
    titles: ['Violet Evergarden'],
    franchiseId: 'violet-evergarden',
    domain: 'emotional drama',
    subdomain: 'healing through letters',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['emotional'],
    avoidDomains: [],
    successors: [],
    note: 'A beautiful emotional drama about grief, war, and learning feelings through letters.'
  },
  {
    id: 'your-lie-in-april',
    titles: ['Your Lie in April'],
    franchiseId: 'your-lie-in-april',
    domain: 'music drama',
    subdomain: 'grief romance performance',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['music'],
    avoidDomains: [],
    successors: [],
    note: 'Music, grief, romance, trauma, and emotional performance.'
  },
  {
    id: 'clannad',
    titles: ['Clannad'],
    franchiseId: 'clannad',
    domain: 'romance drama',
    subdomain: 'family emotional devastation',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['romance'],
    avoidDomains: [],
    successors: [],
    note: 'A romance and family drama famous for emotional devastation.'
  },
  {
    id: 'march-comes-in-like-a-lion',
    titles: ['March Comes in Like a Lion'],
    franchiseId: 'march-comes-in-like-a-lion',
    domain: 'slice of life drama',
    subdomain: 'depression healing shogi',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['slice'],
    avoidDomains: [],
    successors: [],
    note: 'Quiet healing, depression, found family, and competitive shogi.'
  },
  {
    id: 'ancient-magus-bride',
    titles: ['The Ancient Magus\' Bride'],
    franchiseId: 'ancient-magus-bride',
    domain: 'fantasy romance',
    subdomain: 'healing magical folklore',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['fantasy'],
    avoidDomains: [],
    successors: [],
    note: 'Slow magical healing, folklore, loneliness, and strange beauty.'
  },
  {
    id: 'apothecary-diaries',
    titles: ['The Apothecary Diaries'],
    franchiseId: 'apothecary-diaries',
    domain: 'historical mystery',
    subdomain: 'court intrigue medical detective',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['historical'],
    avoidDomains: [],
    successors: [],
    note: 'Palace intrigue, medicine, mystery, and a brilliant poison nerd.'
  },
  {
    id: 'spice-and-wolf',
    titles: ['Spice and Wolf'],
    franchiseId: 'spice-and-wolf',
    domain: 'fantasy economics',
    subdomain: 'travel romance trade politics',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['fantasy'],
    avoidDomains: [],
    successors: [],
    note: 'Economics, travel romance, bargaining, and warm fantasy companionship.'
  },
  {
    id: 'bocchi-the-rock',
    titles: ['Bocchi the Rock!'],
    franchiseId: 'bocchi-the-rock',
    domain: 'music comedy',
    subdomain: 'social anxiety band growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['music'],
    avoidDomains: [],
    successors: [],
    note: 'Social anxiety, band comedy, friendship, and painfully relatable awkwardness.'
  },
  {
    id: 'k-on',
    titles: ['K-On!'],
    franchiseId: 'k-on',
    domain: 'slice of life music',
    subdomain: 'cute band comfort',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['slice'],
    avoidDomains: [],
    successors: [],
    note: 'Comfort food anime about friendship, music, tea, and low-stakes joy.'
  },
  {
    id: 'spy-family',
    titles: ['Spy x Family'],
    franchiseId: 'spy-family',
    domain: 'comedy action',
    subdomain: 'fake family spy comedy',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['comedy'],
    avoidDomains: [],
    successors: [],
    note: 'Fake family, spies, assassins, psychic children, and wholesome chaos.'
  },
  {
    id: 'hinamatsuri',
    titles: ['Hinamatsuri'],
    franchiseId: 'hinamatsuri',
    domain: 'comedy slice of life',
    subdomain: 'yakuza psychic found family',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['comedy'],
    avoidDomains: [],
    successors: [],
    note: 'Deadpan comedy, psychic chaos, yakuza parenting, and surprising heart.'
  },
  {
    id: 'nichijou',
    titles: ['Nichijou'],
    franchiseId: 'nichijou',
    domain: 'surreal comedy',
    subdomain: 'absurd everyday chaos',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['surreal'],
    avoidDomains: [],
    successors: [],
    note: 'Everyday life turned into maximum absurdist comedy.'
  },
  {
    id: 'gintama',
    titles: ['Gintama'],
    franchiseId: 'gintama',
    domain: 'comedy action',
    subdomain: 'samurai parody chaos',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['comedy'],
    avoidDomains: [],
    successors: [],
    note: 'Meta comedy, parody, action, emotional arcs, and complete nonsense.'
  },
  {
    id: 'kaguya-sama',
    titles: ['Kaguya-sama: Love is War'],
    franchiseId: 'kaguya-sama',
    domain: 'romcom',
    subdomain: 'romantic mind games',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['romcom'],
    avoidDomains: [],
    successors: [],
    note: 'Romance as psychological warfare between two proud idiots.'
  },
  {
    id: 'toradora',
    titles: ['Toradora!'],
    franchiseId: 'toradora',
    domain: 'romance drama',
    subdomain: 'tsundere emotional growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['romance'],
    avoidDomains: [],
    successors: [],
    note: 'Romantic comedy with sharp character growth and emotional payoff.'
  },
  {
    id: 'horimiya',
    titles: ['Horimiya'],
    franchiseId: 'horimiya',
    domain: 'romance slice of life',
    subdomain: 'comfortable relationship growth',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['romance'],
    avoidDomains: [],
    successors: [],
    note: 'Warm romance about hidden sides, comfort, and everyday intimacy.'
  },
  {
    id: 'fruits-basket',
    titles: ['Fruits Basket'],
    franchiseId: 'fruits-basket',
    domain: 'romance drama',
    subdomain: 'curse healing family trauma',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['romance'],
    avoidDomains: [],
    successors: [],
    note: 'Healing trauma, family curses, romance, and emotional catharsis.'
  },
  {
    id: 'monogatari',
    titles: ['Monogatari Series'],
    franchiseId: 'monogatari',
    domain: 'supernatural dialogue',
    subdomain: 'wordplay trauma oddities',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Dialogue-heavy supernatural character studies about trauma, desire, and oddities.'
  },
  {
    id: 'baccano',
    titles: ['Baccano!'],
    franchiseId: 'baccano',
    domain: 'crime fantasy',
    subdomain: 'nonlinear immortal gangster chaos',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['crime'],
    avoidDomains: [],
    successors: [],
    note: 'Nonlinear gangster chaos, immortals, trains, and violent fun.'
  },
  {
    id: 'durarara',
    titles: ['Durarara!!'],
    franchiseId: 'durarara',
    domain: 'urban ensemble',
    subdomain: 'city myth network chaos',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['urban'],
    avoidDomains: [],
    successors: [],
    note: 'Urban legends, gangs, online identity, and ensemble chaos.'
  },
  {
    id: 'flcl',
    titles: ['FLCL'],
    franchiseId: 'flcl',
    domain: 'coming-of-age surrealism',
    subdomain: 'puberty rock chaos',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['coming-of-age'],
    avoidDomains: [],
    successors: [],
    note: 'Coming-of-age confusion as surreal rock-powered insanity.'
  },
  {
    id: 'land-of-the-lustrous',
    titles: ['Land of the Lustrous'],
    franchiseId: 'land-of-the-lustrous',
    domain: 'fantasy sci-fi',
    subdomain: 'identity body transformation',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['fantasy'],
    avoidDomains: [],
    successors: [],
    note: 'Beautiful, strange identity fantasy about bodies, purpose, and change.'
  },
  {
    id: 'shinsekai-yori',
    titles: ['Shinsekai Yori'],
    franchiseId: 'shinsekai-yori',
    domain: 'dark sci-fi',
    subdomain: 'society mystery dystopia',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A disturbing slow-burn dystopia about society, power, and buried truth.'
  },
  {
    id: 'serial-experiments-lain',
    titles: ['Serial Experiments Lain'],
    franchiseId: 'serial-experiments-lain',
    domain: 'psychological sci-fi',
    subdomain: 'internet identity alienation',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['psychological'],
    avoidDomains: [],
    successors: [],
    note: 'Internet identity, isolation, reality breakdown, and digital dread.'
  },
  {
    id: 'magi',
    titles: ['Magi'],
    franchiseId: 'magi',
    domain: 'fantasy adventure',
    subdomain: 'kingdom politics dungeon magic',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['fantasy'],
    avoidDomains: [],
    successors: [],
    note: 'Colorful fantasy adventure that opens into politics, kingdoms, destiny, and huge worldbuilding.'
  },
  {
    id: 'kingdom',
    titles: ['Kingdom'],
    franchiseId: 'kingdom',
    domain: 'historical war',
    subdomain: 'military ambition strategy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['historical'],
    avoidDomains: [],
    successors: [],
    note: 'War, ambition, battlefield tactics, and rising through history by force of will.'
  },
  {
    id: 'fate-zero',
    titles: ['Fate/Zero'],
    franchiseId: 'fate-zero',
    domain: 'dark fantasy battle royale',
    subdomain: 'ideology war tragedy',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['dark'],
    avoidDomains: [],
    successors: [],
    note: 'A dark battle royale where ideology, tragedy, and magic collide.'
  },
  {
    id: 'fate-stay-night-ubw',
    titles: ['Fate/stay night: Unlimited Blade Works'],
    franchiseId: 'fate-stay-night-ubw',
    domain: 'urban fantasy battle royale',
    subdomain: 'hero ideals magic war',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['growth', 'rivalry'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['urban'],
    avoidDomains: [],
    successors: [],
    note: 'Stylish urban magic combat about ideals, heroes, and impossible standards.'
  },
  {
    id: 'moriarty-the-patriot',
    titles: ['Moriarty the Patriot'],
    franchiseId: 'moriarty-the-patriot',
    domain: 'crime mystery',
    subdomain: 'antihero class rebellion',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['crime'],
    avoidDomains: [],
    successors: [],
    note: 'Sherlock-style crime intrigue from the villain\'s side with class-war energy.'
  },
  {
    id: 'odd-taxi',
    titles: ['Odd Taxi'],
    franchiseId: 'odd-taxi',
    domain: 'mystery drama',
    subdomain: 'talky animal noir puzzle',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mystery'],
    avoidDomains: [],
    successors: [],
    note: 'A deceptively simple mystery with sharp dialogue and tightly woven reveals.'
  },
  {
    id: 'summertime-rendering',
    titles: ['Summertime Rendering'],
    franchiseId: 'summertime-rendering',
    domain: 'mystery thriller',
    subdomain: 'island time-loop horror',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mystery'],
    avoidDomains: [],
    successors: [],
    note: 'Island mystery, time loops, horror tension, and escalating strategy.'
  },
  {
    id: 'vivy',
    titles: ['Vivy: Fluorite Eye\'s Song'],
    franchiseId: 'vivy',
    domain: 'sci-fi action',
    subdomain: 'AI time mission music',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['sci-fi'],
    avoidDomains: [],
    successors: [],
    note: 'AI, music, time missions, and emotional sci-fi action.'
  },
  {
    id: 'cyberpunk-edgerunners',
    titles: ['Cyberpunk: Edgerunners'],
    franchiseId: 'cyberpunk-edgerunners',
    domain: 'cyberpunk tragedy',
    subdomain: 'crew downfall neon violence',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['cyberpunk'],
    avoidDomains: [],
    successors: [],
    note: 'Neon violence, found family, body modification, and doomed ambition.'
  },
  {
    id: '86',
    titles: ['86'],
    franchiseId: '86',
    domain: 'military sci-fi',
    subdomain: 'war trauma discrimination',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['military'],
    avoidDomains: [],
    successors: [],
    note: 'Mecha war trauma, prejudice, survival, and emotional military drama.'
  },
  {
    id: 'gundam-wing',
    titles: ['Gundam Wing'],
    franchiseId: 'gundam-wing',
    domain: 'mecha political war',
    subdomain: 'pilot ideology conflict',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mecha'],
    avoidDomains: [],
    successors: [],
    note: 'Stylish mecha pilots, politics, ideology, and war drama.'
  },
  {
    id: 'gundam-iron-blooded-orphans',
    titles: ['Mobile Suit Gundam: Iron-Blooded Orphans'],
    franchiseId: 'gundam-iron-blooded-orphans',
    domain: 'mecha war drama',
    subdomain: 'child soldiers found family',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['mecha'],
    avoidDomains: [],
    successors: [],
    note: 'Child soldiers, found family, brutal politics, and mecha tragedy.'
  },
  {
    id: 'soul-eater',
    titles: ['Soul Eater'],
    franchiseId: 'soul-eater',
    domain: 'supernatural action',
    subdomain: 'gothic weapon school style',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Gothic style, weapon partners, Halloween energy, and battle-school fun.'
  },
  {
    id: 'fire-force',
    titles: ['Fire Force'],
    franchiseId: 'fire-force',
    domain: 'supernatural action',
    subdomain: 'firefighter demon combat',
    setting: [],
    mood: ['hype', 'emotional'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['supernatural'],
    avoidDomains: [],
    successors: [],
    note: 'Fire-powered action, religious mystery, squads, and explosive fights.'
  },
  {
    id: 'dr-stone',
    titles: ['Dr. Stone'],
    franchiseId: 'dr-stone',
    domain: 'science adventure',
    subdomain: 'civilization rebuilding',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['science'],
    avoidDomains: [],
    successors: [],
    note: 'Science, rebuilding civilization, problem solving, and clever invention.'
  },
  {
    id: 'food-wars',
    titles: ['Food Wars!'],
    franchiseId: 'food-wars',
    domain: 'competition comedy',
    subdomain: 'cooking battle exaggeration',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['competition'],
    avoidDomains: [],
    successors: [],
    note: 'Cooking battles treated like shonen fights with absurd reactions.'
  },
  {
    id: 'mashle',
    titles: ['Mashle'],
    franchiseId: 'mashle',
    domain: 'magic school parody',
    subdomain: 'muscle comedy battle school',
    setting: [],
    mood: ['focused', 'distinctive'],
    atmosphere: ['stylish', 'memorable'],
    themes: ['identity', 'worldbuilding'],
    characterArchetypes: [],
    musicIdentity: [],
    pacing: 'series-specific',
    mustMatchDomains: ['magic'],
    avoidDomains: [],
    successors: [],
    note: 'A magic-school parody where muscles solve wizard problems.'
  }
];
